### ISSUE TITLE
Feature Request: Rollback secrets version

### ISSUE THREAD

**Issue by omerxx** [segmentio/chamber#100]
Since chamber stores on SSM and the secrets gets their versions incremented, I'd like to have the option to revert the keys to a previous version with something like `chamber revert <service> <key>`

Relevant use case: I've updated a secret / env variable with chamber, then the deployed production service fails to load due to the bad key, I'd like to quickly have the option to revert.
In my case, I'd be doing it as a logical step in my CI deployment process:
1. Sync keys and variables using `chamber import`
2. Deploy version to production
3. If version fails *revert chamber changes*

**Comment by nickatsegment** [comment]
It's not on anyone's roadmap as far as I know.

**Comment by omerxx** [comment]
@nickatsegment Thanks for the answer. Just presented chamber in a meetup yesterday and it came up as a question from the crowd.
