### ISSUE TITLE
Warn if SSM API requests are throttled

### ISSUE THREAD

**Issue by otterley** [segmentio/chamber#101]
Under normal operation, the SSM API will respond reasonably quickly to requests.  

When SSM API requests are throttled, Chamber currently retries the requests up to the configured retry count. While it does so, no output is returned to the user, and Chamber appears to hang in the meantime.

It would be useful to know when Chamber is retrying the requests so that the user can know that progress is being made.  This can help rule out other potential problems such as network connectivity or other issues.  Otherwise, the user is only aware of the symptom of the problem (hanging) and has no indication of the cause.

**Comment by nickatsegment** [comment]
I think hanging and not telling the user there's bad stuff happening is a bug. At the very least it should be in the debug log.

**Comment by ohookins** [comment]
Would really like to have this feature! It's very hard to understand what is happening when Chamber does not work as expected!
