### ISSUE TITLE
Write insecure parameters

### ISSUE THREAD

**Issue by robinbowes** [segmentio/chamber#105]
Any chance of adding a mechanism to use chamber to manage insecure parameters?

**Comment by otterley** [comment]
Can you discuss your use case?

**Comment by robinbowes** [comment]
Purely convenience, ie. using the same tool to manage unsecured SSM Parameters.

**Comment by otterley** [comment]
Is there a particular reason not to secure those parameters?

**Comment by robinbowes** [comment]
Again, convenience when browsing parameters using the console.

**Comment by otterley** [comment]
I think we're unlikely to add support for this. 

First, the purpose of Chamber is to make it easy for application developers to access secrets held in Parameter Store.  We want to promote best practices with respect to secret management, and that includes enforcing encryption both at rest and in transit.  We don't want to make it easy not to use encryption as we discourage such practices.

We recognize that sometimes exceptions must be made, which is why I expressed interest in your use case.  But here, "convenience" has been cited as the only factor - your request lacks detail as to a specific scenario (either real or hypothetical) where encryption would be significantly burdensome or problematic.

**Comment by moaazsidat** [comment]
+1 for non-encrypted variables support. 

chamber makes it easy to import and manage variables via SSM, which supports both encrypted and non-encrypted variables to be stored and fetched, and it may make sense to support similar within chamber. 

one particular reasoning for supporting non-encrypted variables is micro-managing costs around decrypting variables using KMS. If a developer knows that a particular variable is safe to be stored as a non-encrypted variable in SSM, it may make sense for chamber to support that behaviour. 

wondering if that is a sound reasoning, welcoming further thoughts on the issue

**Comment by abraithwaite** [comment]
> one particular reasoning for supporting non-encrypted variables is micro-managing costs around decrypting variables using KMS. If a developer knows that a particular variable is safe to be stored as a non-encrypted variable in SSM, it may make sense for chamber to support that behaviour.

You should check out the new S3 backend.  There should be no reason with the new backend not to throw everything in chamber, even non-sensitive variables.

**Comment by nickatsegment** [comment]
I wonder if reading from unencrypted stuff works as written now? I don't know if there's anything that would stop you doing e.g. `chamber read` on an unencrypted S3 bucket.

I would however object to being able to do `chamber write` in an unencrypted way. Seems like a good way to shoot yourself in the foot, and not really worth the use case.

**Comment by caleb15** [comment]
> Seems like a good way to shoot yourself in the foot

As long as you have to intentionally specify that you want it unencrypted I don't see the issue. Especially if you name it something like --use-horribly-insecure-no-encryption-oh-god-why-are-you-even-doing-this or add a warning :P

> not really worth the use case.

There's multiple use-cases with this. It may be useless to you, but it's still useful to some people.
* Cost savings
* Ability to see safe value without having to do a extra click to show it in the website console
* Ability to let people see safe SSM vars without needing to give them KMS access for decrypting sensitive vars

**Comment by nickatsegment** [comment]
> There's multiple use-cases with this. It may be useless to you, but it's still useful to some people.

I didn't say it's useless. I said it's outside the scope of chamber, which is for secrets.

**Comment by caleb15** [comment]
> I didn't say it's useless

My bad, I should have said "It may not be worth the use case to you..." Point is I think it's worth the use case, and some others do too. Not saying you should bother adding it, but It's worth accepting a PR if someone really wants it IMO.

> I said it's outside the scope of chamber, which is for secrets.

Plaintext values are technically still "secrets" in that only the company who has access to those values knows about them. Admittedly this is stretching the definition a little :sweat_smile:  (ok, a lot)
