### ISSUE TITLE
Passwords that contain "$" will be sliced if not wrapped. (ZSH)

### ISSUE THREAD

**Issue by omerxx** [segmentio/chamber#106]
**Reproduce:**
Putting a problematic key:
`chamber write test password prefix$something+suffix`
Fetching:
`chamber read test password -q`
Will turn out as `prefix+suffix`

**Workaround:**
Setting an escape char `\` before `$`:
`chamber write test password prefix\$something+suffix`
I guess it should be implemented as a fix. Don't know if that's golang or SSM's reponsibility

**Comment by alberts** [comment]
@omerxx I think you might be running afoul of your shell here.

Try chamber write test password 'prefix$something+suffix'

**Comment by omerxx** [comment]
@alberts You are right, although `"` had the same problem. anyway `'` is a solution. Thanks

**Comment by nickatsegment** [comment]
By the time the arg gets to chamber, the shell will have already done the substitution. I'm pretty sure there's nothing chamber can do to help @omerxx; you'll have to quote it or escape it.
