### ISSUE TITLE
SSM parameter labels

### ISSUE THREAD

**Issue by jdub** [segmentio/chamber#107]
One concern I've had with Chamber (and similar tools) is that configuration changes can cause interruptions to service just like code changes, so should ideally be versioned and deployed in a similar way.

SSM now has a solution for this, in the form of [parameter labels](https://aws.amazon.com/blogs/mt/use-parameter-labels-for-easy-configuration-update-across-environments/).

What could Chamber support for this look like?

```bash
chamber exec <service> [--label <label>] -- <executable> [args]
```

It might be useful to allow Chamber to return unlabelled parameters too?

**Comment by nickatsegment** [comment]
This seems reasonable to me. The main concern is keeping chamber API-call-efficient. `exec` uses `GetParametersByPath`, which does support filtering by label. (https://github.com/segmentio/chamber/blob/master/store/ssmstore.go#L368) It even takes multiple filters, which I assume must be a set union. I know @dfuentes is working on a couple of new features and this might fit into that work.

**Comment by DanielRedOak** [comment]
I am interested in this as our use of Chamber becomes a reality. Has anyone else started work on this at all?

**Comment by nickatsegment** [comment]
@DanielRedOak 	I don't think so. I've added the `helpwanted` label, and if someone wants to give it a go, I'll remove it.

**Comment by pecigonzalo** [comment]
I believe `GetParametersByPath` does support it, check the example in the linked document:

`--parameter-filters Key=Label,Values=Current,Option=Equals`

We should be able to set them as:
https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#GetParametersByPathInput

**Comment by pecigonzalo** [comment]
I just pushed and PRd a simple/test implementation.
