### ISSUE TITLE
On AWS, chamber overwrites description for SSM parameters

### ISSUE THREAD

**Issue by kallja** [segmentio/chamber#108]
Apparently chamber uses AWS description field for versioning. I find this behavior unexpected because it overwrites any text content on `chamber write`. Additionally SSM parameters have a managed version field provided and maintained by AWS.

If there's reasonable rationale for using the description field to track versions, I suggest you add a command line flag to prevent this behavior.

**Comment by ldormoy** [comment]
I am dumbfounded, why misusing the description field when there is a dedicated proper version field already existing?

This is quite dangerous as a simple `aws ssm put-parameter --overwrite` command will corrupt an existing chamber key.

**Comment by dfuentes** [comment]
When chamber was originally written, there was no version field for SSM parameters, hence using the description field to insert our own.

A fix to this would need to be careful to maintain backwards compatibility with existing chamber written parameters.

**Comment by mckern** [comment]
Closing; still attached to the `v3` milestone and may be revisited in the future.
