### ISSUE TITLE
Sort keys when listing

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/chamber#110]
Currently, the sort order for listing keys appears random (though it's probably the order that AWS lists things). In any case, I think sorting by name is the most sensible thing, especially since you can't pipe that command through `sort` atm. I could also see viability for sorting by mtime, though I honestly prefer the former.

**Comment by mckern** [comment]
Closing; `export` and `env` list keys alphabetically for now, and we may revisit this in the future.
