### ISSUE TITLE
Running inside lambda

### ISSUE THREAD

**Issue by dgoradia** [segmentio/chamber#113]
Can the chamber binary run inside a lambda function? 

When I tried to read a secret it just exits out with status 1, no error message

Has anyone done this already?

**Comment by boggsboggs** [comment]
If you're running a go program, you can import chamber as a library and read the secrets directly. You can also read the SSM parameters directly using aws libraries from any other language.

Lambas don't have access to operating system features like environment variables or exec, so running chamber in a lambda doesn't really make sense. #serverless

**Comment by boggsboggs** [comment]
I initially thought this wasn't possible and answered this question as such. But, after some second thoughts and AWS lambda research, I realized that it is possible, deleted my reply, and setup an example lambda function.

I got chamber to work on lambda via a python2.7 function that started a chamber subprocess that called exec on a statically linked binary that was included with the lambda .zip.

The python file was this:
```
import subprocess

def lambda_function(event, context):
    try:
        return subprocess.check_output(['./chamber', 'exec', 'test', '--', './print-env-binary'], stderr=subprocess.STDOUT)
    except Exception as e:
        print 'error output: ', e.output
        raise
```

The `print-env-binary` was from this go code 
```
// https://gobyexample.com/environment-variables
package main

import "os"

import "fmt"

func main() {
	// Use `os.Environ` to list all key/value pairs in the
	// environment. This returns a slice of strings in the
	// form `KEY=value`. You can `strings.Split` them to
	// get the key and value. Here we print all the keys.
	fmt.Println()
	for _, e := range os.Environ() {
		fmt.Println(e)
	}
}
```
which had been compiled, statically linked, for linux with `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o print-env-binary`

The .zip I uploaded to lambda included chamber and the compiled print-env-binary, so all together it looked like this:
```
lambda-test
lambda-test/print-env-binary
lambda-test/lambda_module.py
lambda-test/chamber
lambda-test/main.go
```

I had to give the lambda role access to SSM and KMS to read the secret cipher text and master key. This is the same as using chamber elsewhere.

**Comment by dgoradia** [comment]
Thanks, worked great.
