### ISSUE TITLE
Feature Request: Ability to run chamber exec without credentials with environment variable

### ISSUE THREAD

**Issue by albertpaulp** [segmentio/chamber#115]
I'm using chamber for production, staging environments now. I use chamber along with Docker. I use same docker image for Production, Staging and development/local, however there is a problem with this setup. chamber errors out if I run `chamber exec` without setting it up initially. I don't want to store my development/local environment secrets as it change often and other developers use their own secrets.

Proposed solution is using a environment variable like `CHAMBER_DEVELOPMENT_MODE` to change Chamber behaviour, so that it won't fail and execute the command passed in even if chamber not configured.

I'm a ruby developer and I'm completely new to Go else I would've submitted a MR along with this. It'll be very helpful if we can have this feature.

**Comment by nickatsegment** [comment]
@albertpaulp what set up are you talking about specifically? The KMS key? AWS auth stuff?

**Comment by albertpaulp** [comment]
@osterman Sorry for radio silence, yes it does.
