### ISSUE TITLE
Using chamber with terraform tip

### ISSUE THREAD

**Issue by conzy** [segmentio/chamber#117]
Just want to say thank you for chamber. It has made adopting aws parameter store a breeze for us.

Terraform expects variables to be passed via the environment like this `TF_VAR_the_variable`

I have lots of terraform modules that expect a database password or some secret. I put the secrets in parameter store under a `/terraform/` namespace. I can then inject secrets into terraform at run time with this simple script called `terrachamber`

```ruby
#!/usr/bin/env ruby

# Takes a terraform / terragrunt command as an argument.
# Uses a system call to grab terraform secrets from AWS parameter store via chamber
# Injects those secrets into the environment in the terraform variable format i.e TF_VAR_the_variable
# Performs a system call of the argument array that is passed
#
# Usage Examples
#
#  terrachamber terraform apply
#  terrachamber terragrunt apply --terragrunt-source-update
#  aws-vault exec dev-admin -- terrachamber terraform apply
#

require 'json'

JSON.parse(`chamber export terraform`).each {|k,v| ENV["TF_VAR_#{k}"] = v}
system(*ARGV)
```

This may help someone else. But this is also a feature request :)

If you could chose the output format of chamber that would be wonderful. e.g I could do the above natively with chamber if it supported a key prefix and if it supported the ability to not capitalise the environment variables.

Something like:

`chamber exec --prefix TF_VAR_ --no-capitalise namespace -- terraform apply`

That would take my secrets:

```
/terraform/database_password
/terraform/big_secret
```
And export them like this:

```
TF_VAR_database_password
TF_VAR_big_secret
```

This may be beyond the scope of chamber. But it already supports json output etc.

Thanks!

**Comment by nickatsegment** [comment]
Sounds reasonable to me. I wonder if a general `--format` flag with templating would work, so you could do something like
```
chamber exec --format 'TF_VAR_{{.}}'
```
where the default is `{{. | upper }}`

**Comment by systemizer** [comment]
Hey @conzy !

Thanks for your thoughts here. As mentioned in a [similar PR](https://github.com/segmentio/chamber/pull/130#issuecomment-419538123) , we have decided variable transforms are outside the scope of chamber. We recommend applying formatting either within your code or via a intermediate formatting tool.

Let me know if this makes sense. Thanks again!

**Comment by nickatsegment** [comment]
Sorry for leading everybody on :)

**Comment by calebgosnell** [comment]
Am I missing something, or wouldn't storing a secret in`/terraform/TF_VAR_database_password`
populate the env variable `TF_VAR_database_password` ?

**Comment by nickatsegment** [comment]
@calebgosnell 	That's correct. The desired behavior is to chamber export the env var with the same case as when stored, since terraform requires lowercase

**Comment by conzy** [comment]
@calebgosnell We have dozens of existing TF variables that are lowercase and we use a few community modules too that expect lowercase variables. So the usual chamber pattern of variables being exported in uppercase does not work for this use case

**Comment by osterman** [comment]
We wrote tfenv (similar to terrachamber) to accommodate this use-case of transforming variables for consumption with terraform:
https://github.com/cloudposse/tfenv

It also supports mapping of TF_CLI arguments.
