### ISSUE TITLE
SSMStore should validate on write as well

### ISSUE THREAD

**Issue by pecigonzalo** [segmentio/chamber#119]
As discussed on #118 `SSMStore` currently only validates on `list` to know which values to retrieve and otherwise continue.
We should probably update it so it validates on `write` as well, matching valid formats that:
- AWS SSM Supports
- We can read back

This could also include combining the validation done on both `root` and `ssm_store` into the same, as they are tightly related and to ensure they match.

**Comment by nickatsegment** [comment]
Fixed by #118 I think.
