### ISSUE TITLE
Feature request: chamber upgrade <service>

### ISSUE THREAD

**Issue by sjauld** [segmentio/chamber#133]
This feature would upgrade a service from v1 style (CHAMBER_NO_PATHS) to v2 style (CHAMBER_USE_PATHS), thereby allowing users to easily and safely upgrade chamber.

**Comment by nickatsegment** [comment]
`export | import` should work fine? https://github.com/segmentio/chamber#20-breaking-changes I don't think we need anything more complicated than that
