### ISSUE TITLE
No error when invalid service name provided

### ISSUE THREAD

**Issue by shaunokeefe** [segmentio/chamber#142]
Currently when `exec`, `list` and `export` are called with an invalid service name (i.e. one that doesn't exist) the command quietly exits and returns `0`, without loading any secrets and without signalling a failure.

It's fairly common for us to get tripped up by this. For example, if we're standing up a new service and are running the same script on multiple AWS accounts and we've forgotten to create the chamber service in each account.

A nice quick failure if we were asking chamber to load an invalid service would save a lot of debugging time. Currently we only first see a failure when env variables aren't set and we get an error in our config code, or worse, it quietly falls back to defaults, and we usually have to spend a bit of time working back from the failure to realising we've mucked up our environment config.

**Comment by osterman** [comment]
If this is implemented, it should be optional. We use this in our favor. 
E.g. 
```
chamber exec "$APP" "$APP_PR${PR_NUMBER}" -- myapp
```
Which lets us *optionally* override the envs for a particular PR by setting them in the `$APP_PR$PR_NUMBER` service namespace for a partifucal pull request.

**Comment by nickatsegment** [comment]
Here's a silly workaround:

```
sh -ec '[ ! -z $(chamber export $SERVICE -f dotenv) ] && chamber exec $SERVICE -- ./service'
```
