### ISSUE TITLE
`go get -u` failing

### ISSUE THREAD

**Issue by tsvanharen** [segmentio/chamber#145]
Using `go get -u github.com/segmentio/chamber` seems to be failing with the following error:

> package gopkg.in/segmentio/analytics-go.v3/vendor/github.com/segmentio/backo-go: gopkg.in/segmentio/analytics-go.v3 is a custom import path for https://gopkg.in/segmentio/analytics-go.v3, but GOPATH/src/gopkg.in/segmentio/analytics-go.v3/vendor/github.com/segmentio/backo-go is checked out from https://github.com/segmentio/backo-go
> package gopkg.in/segmentio/analytics-go.v3/vendor/github.com/xtgo/uuid: gopkg.in/segmentio/analytics-go.v3 is a custom import path for https://gopkg.in/segmentio/analytics-go.v3, but GOPATH/src/gopkg.in/segmentio/analytics-go.v3/vendor/github.com/xtgo/uuid is checked out from https://github.com/xtgo/uuid

This issue may have been introduced in this PR:  https://github.com/segmentio/chamber/pull/139

**Comment by tsvanharen** [comment]
@systemizer, that worked!  Thanks.

**Comment by nickatsegment** [comment]
Hm, the tests show this should have worked; perhaps they're not good enough
https://circleci.com/gh/segmentio/chamber/339
https://circleci.com/gh/segmentio/chamber/338
https://circleci.com/gh/segmentio/chamber/336

@tsvanharen What version of Go are you running?

**Comment by nickatsegment** [comment]
@tsvanharen 	I'm considering deprecating the `go get` installation method and would love your feedback at https://github.com/segmentio/chamber/issues/164
