### ISSUE TITLE
Feature Request: Read capability for ease of use

### ISSUE THREAD

**Issue by sc-chad** [segmentio/chamber#15]
Love this project!  This solved a very complex problem with a very simple solution.

One thing I would like is an easy way to just read a parameter.  

I know you can do something like: ```chamber exec foo_bar -- echo $BAR``` but that seems overly complex instead of doing something like ```chamber read foo_bar```

**Comment by ejcx** [comment]
Hey @sc-chad, I agree that this is worthwhile especially for debugging. Would love to hear if #17 fits your needs.

**Comment by ejcx** [comment]
Think we're good here. We will cut a release in the morning
