### ISSUE TITLE
chamberstag read -q service db-pass panic: unable to redefine 'v' shorthand in "read" flagset: it's already used for "version" flag

### ISSUE THREAD

**Issue by Gavin89** [segmentio/chamber#151]
when I run chamberstag write stag db-password test it correctly adds db-password to my parameter store. However, when running chamberstag read stag db-password, I get the following.

panic: unable to redefine 'v' shorthand in "read" flagset: it's already used for "version" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0001e4300, 0xc0000d5f40)
	/Users/gavinhardy/go/src/github.com/spf13/pflag/flag.go:862 +0x6e5
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc0000d5f40)
	/Users/gavinhardy/go/src/github.com/spf13/pflag/flag.go:875 +0x6f
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc0001e4800, 0xc0001ddba0)
	/Users/gavinhardy/go/src/github.com/spf13/pflag/flag.go:278 +0x97
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc0001e4300, 0xc0001e4800)
	/Users/gavinhardy/go/src/github.com/spf13/pflag/flag.go:873 +0x58
github.com/spf13/cobra.(*Command).mergePersistentFlags(0x1c5bc80)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:1495 +0x90
github.com/spf13/cobra.stripFlags(0xc0000bcfa0, 0x2, 0x2, 0x1c5bc80, 0x2, 0x0, 0x2)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:474 +0x51
github.com/spf13/cobra.(*Command).Find.func1(0x1c5bc80, 0xc0000bcfa0, 0x2, 0x2, 0x4, 0xc0000bcfa0, 0x2, 0x2)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:533 +0x5c
github.com/spf13/cobra.(*Command).Find.func1(0x1c5bee0, 0xc0000c60d0, 0x3, 0x3, 0x16fd374, 0x29, 0xc0000f6200, 0x73)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:541 +0x119
github.com/spf13/cobra.(*Command).Find(0x1c5bee0, 0xc0000c60d0, 0x3, 0x3, 0x3, 0x3, 0xc0000c4e60, 0xd, 0xc0001dde90, 0x1041cf1)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:546 +0xab
github.com/spf13/cobra.(*Command).ExecuteC(0x1c5bee0, 0xc0001ddf00, 0xc0001ddf88, 0x10071b0)
	/Users/gavinhardy/go/src/github.com/spf13/cobra/command.go:833 +0x64b
github.com/segmentio/chamber/cmd.Execute(0x16e9034, 0x3)
	/Users/gavinhardy/go/src/github.com/segmentio/chamber/cmd/root.go:57 +0x56
main.main()
	/Users/gavinhardy/go/src/github.com/segmentio/chamber/main.go:11 +0x39

**Comment by systemizer** [comment]
Hi @Gavin89 

Can you try updating chamber? We ran into this issue a couple weeks back and committed a fix.

**Comment by Gavin89** [comment]
Worked!, thank you.
