### ISSUE TITLE
Discussion regarding alternative/unique values per docker deploy

### ISSUE THREAD

**Issue by maartenvanderhoef** [segmentio/chamber#154]
Hi Everyone,

There is [this recent medium Article](https://medium.com/airbnb-engineering/production-secret-management-at-airbnb-ad230e1bc0f6) from Airbnb about their secret Management. Non conform factor12 they pack their secrets in an encrypted file and let the application handle it when deployed.

I've commented the article with a question to the author if they thought about SSM/KMS and the answer was that there are cases that one wants to be able to deploy to different values. In the Airbnb case the deployment could decide which Database it connects to etc, a rollback would make it possible to then also rollback to the previous DB and so on. I do not like the databag idea, but there is something to say for having 2 similar docker deployments but with alternative values. Like with ECS and ENV vars, the ENV vars are deployed per ECS Task definition, and not per ECS Service.

I have some ideas on how to make chamber semi-compatible with that kind of mindset, would like to know first what the thoughts are... Cheers!

**Comment by nickatsegment** [comment]
I'm not really clear on what you're asking about here, with respect to chamber.

At Segment, we have non-secret configuration for each environment stored in the codebase that gets baked into the Docker image with every build. We use this to do rollbacks all the time, using ECS services, task definitions, etc. Secrets are, of course, injected by chamber at runtime.

**Comment by maartenvanderhoef** [comment]
Hi @nickatsegment thanks for responding. I've gone a different angle, never differentiated between secrets and regular ENV vars. From the beginning I've stored everything in SSM, Terraform creates the service, database, and populates all needed SSM variables. This creates one source of truth which worked out well for all developers.
Also the workflow is straight forward for us as Terraform creates the database, and so it can also create the DATABASE_HOST ssm variable etc.etc..

If Chamber had an override mechanism which allows for certain values to come from a different source, like a different SSM path, it can then offer the same flexibility to have deployment specific values as Segment has with having it built into Docker.
