### ISSUE TITLE
Load service name from ENV var

### ISSUE THREAD

**Issue by lleger** [segmentio/chamber#159]
Currently running `chamber exec` requires you to pass a hardcoded value for the service name:

```bash
chamber exec app -- node server/boot.js
```

Of course, you can always set your own variable:

```bash
$ export CHAMBER_SERVICE=app
$ chamber exec $CHAMBER_SERVICE -- node server/boot.js
```

But setting this in a Dockerfile requires some changes that you may not be tenable:

```dockerfile
CMD [ "sh", "-c", "/usr/local/bin/chamber exec $CHAMBER_SERVICE  -- node server/boot.js" ]
```

It would be really nice if Chamber could read the service name from an ENV var automatically so you didn't have to pass the service name as an option. That would allow you to avoid having to munge the `CMD` option in your Dockerfile:

```dockerfile
CMD [ "chamber", "exec", "--", "node", "server/boot.js" ]
```

It would also make using Chamber in, e.g., ECS environments, where you can push the aforementioned `CMD` option and then set the ENV var via ECS console/API depending on the task definition. This lets you reuse the Dockerfile seamlessly between environments.

**Comment by nickatsegment** [comment]
Is it a big deal to add an entrypoint script?

```
#!/bin/sh

exec chamber exec $CHAMBER_SERVICE -- node server/boot.js $@
```

```
...
ENV CHAMBER_SERVICE=app
ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT /entrypoint.sh
```

**Comment by lleger** [comment]
I mean, yeah, that's just a different workaround from what I posted above. I get your point about having as few knobs as possible, and using the workaround isn't terrible, but since Chamber had other ENV vars I figured it would be worth positing as a use case.

**Comment by nickatsegment** [comment]
I've come to the conclusion that basically every non-trivial docker container needs an entrypoint script to do glue stuff like this.

Frankly I'm not very keen on our use of environment variables all over the place. They're scattered throughout the code base, not as robustly validated, hard to document vs flags, far too implicit, etc.

I get that passing a flag using an env var seems like a small ask. But it complicates the arg parsing code a bit, more than I'd say is worth it.
