### ISSUE TITLE
Null backend requires AWS credentials

### ISSUE THREAD

**Issue by liorhar** [segmentio/chamber#165]
Running chamber with `CHAMBER_SECRET_BACKEND=NULL` errors when AWS credentials aren't configured:
```
Error: Failed to list store contents: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I want to use the Null backend for the development environment and most devs here don't have the AWS credentials configured. 
Is this the expected behaviour?

**Comment by nickatsegment** [comment]
What's the command you're running?

**Comment by liorhar** [comment]
`CHAMBER_SECRET_BACKEND=NULL chamber exec prod -- java -jar build/libs/app.jar`

**Comment by nickatsegment** [comment]
And `chamber version`?

**Comment by liorhar** [comment]
right, v2.2.0.

**Comment by nickatsegment** [comment]
Yeah, the NULL backend was implemented after that. In fact, it's not in a release yet:

```sh
% git log -S NULL
Thu Sep 27 21:26:12 2018 +0200 d2451a0 Addition of a NULL Backend to provide a simple way of disabling backend lookups  [maartenvanderhoef]
% git tag --contains d2451a0
%
```
I might cut a release today actually

**Comment by nickatsegment** [comment]
Hot off the presses: https://github.com/segmentio/chamber/releases/tag/v2.3.1
