### ISSUE TITLE
Feature request: Support variables in parameter store value

### ISSUE THREAD

**Issue by ramakuka** [segmentio/chamber#171]
## What?
Values in parameter store can include variables that should be replaced by Chamber with the value of a local environment variable. 
for example, parameter store key/vale `somekey: randomvalue-$${VAR}}` should be set as `SOMEKEY=randomvaulue-varvalue` by Chamber, assuming `$VAR` environment variable exists and the value is `varvalue`
## Why?
In cases where a reference to an infrastructure specific parameter (e.g host_ip) in a parameter store value is needed.
For example, in our case, an instance ip is required by our application. Kubernetes has a simple way to expose host_ip as an environment variable to the pod. with support for variables on parameter store we can store values like `url=https://$${HOST_IP}/`, and have Chamber replace HOST_IP with the value of the HOST_IP environment variable

**Comment by nickatsegment** [comment]
I don't think this fits with the "chamber is not and env var transformation engine" scope :)

I'm sure you can accomplish this with shell. Here's a start:
```sh
# t=$(tempfile)
# env | envsubst > $t
# env | grep VAR
VAR1=${VAR2}
VAR2=value2
# source $t
# rm $t
# env | grep VAR
VAR1=value2
VAR2=value2
```

**Comment by nickatsegment** [comment]
@ramakuka Chamber is meant for managing secrets. `chamber exec` is an efficient way to inject those secrets into your app via environment variables. It's not meant to be a full-featured configuration management solution. 

You're already running Kubernetes: why not config maps?

You're already building container images: why not add an entrypoint script that does the transforms you're looking for?

**Comment by ramakuka** [comment]
@nickatsegment, I see your point, I think I better understand it now. 
We do not separate secrets from config as we realized they are very similar.
They both need to be injected into the pod, they both depend on the environment and therefore cannot be kept as a static asset (like configMap) and in many cases can be provided to the service by other teams (e.g., the platform team). It means that for us secrets are simply encrypted configs.
The big benefit we see from it is that our service Dockerfiles and kubernetes config can be simplified and even templatized so a change in a core/infrastructure value will not require a change to all the services but only a simple reload.

Hope it shades more light on why the idea behind feature and way we use Chamber.
