### ISSUE TITLE
Question: How can I debug injected values with exec ?

### ISSUE THREAD

**Issue by bonclay7** [segmentio/chamber#177]
Hey there ! 
Thanks for this amazing tool. I have a question concerning using exec to inject environment variables. How would you debug those values in a docker environment, I've tried to look under `/proc` to see values associated with it, but nothing shows up. Do you have any insights ?

**Comment by nickatsegment** [comment]
@bonclay7 	`chamber exec --verbose` tells you what vars are getting set :)
