### ISSUE TITLE
Update AWS SDK to v1.16.0

### ISSUE THREAD

**Issue by jradtilbrook** [segmentio/chamber#180]
I realise you have only just bumped the AWS SDK version to v1.15.90 in #179, but my use case requires the `credential_process` support from the SDK. Would you be willing to accept a PR that bumped it yet again if I provided one?

For reference, the release notes are at https://github.com/aws/aws-sdk-go/releases/tag/v1.16.0

**Comment by alberts** [comment]
PRs welcome!
