### ISSUE TITLE
Display year of last modified date

### ISSUE THREAD

**Issue by forestbelton** [segmentio/chamber#189]
When listing kv pairs with `chamber list`, only the day, month, and time is displayed:

```
Key						Version		LastModified
abcde						1		01-23 15:39:23
...
```

I see that the format string for date display is here: https://github.com/segmentio/chamber/blob/a94b7aa7e9a0796a88d2665bc74a10b1ab94ca35/cmd/root.go#L32

Would it be possible to configure this to also display the year, via command line options or by default? We are getting to the point where we have values close to >1y so it would be great to differentiate there.

**Comment by fdemmer** [comment]
fyi: changed to include year in 4421de337e927d1108c7a1d0208691c2b9088f72
