### ISSUE TITLE
Can't Access ENV Variables

### ISSUE THREAD

**Issue by fifthpostulate** [segmentio/chamber#196]
Am I missing something embarrassingly simple?

$ chamber exec test-service -- env | grep TEST
TEST_KEY=test-value

This returns nothing:
$ chamber exec test-service -- echo $TEST_KEY

**Comment by alberts** [comment]
Try: chamber exec test-service -- bash -c 'echo $TEST_KEY'

I believe your variable is getting interpolated by the shell before chamber runs.

**Comment by fifthpostulate** [comment]
Thanks, @alberts!
