### ISSUE TITLE
Templating support like consul-template

### ISSUE THREAD

**Issue by imranismail** [segmentio/chamber#197]
This looks really good. Thank you so much for this!

If there's support for templating it would be a great way to reach more environment/setup. 

https://www.hashicorp.com/blog/using-vault-with-consul-template
https://github.com/hashicorp/consul-template

**Comment by nickatsegment** [comment]
I don't know that embedding a templating language would provide a lot of value beyond `chamber export | myfavouritetemplater > output`.

`consul-template` is a different beast: it doesn't just do templating, it can watch for changes and re-template. Are you suggesting a `chamber-template` that does something similar?

**Comment by imranismail** [comment]
Didn't think of that. I've decided to pair this up with https://github.com/hairyhenderson/gomplate

Thanks!
