### ISSUE TITLE
chamber exec succeeds even without iam access

### ISSUE THREAD

**Issue by hlarsen** [segmentio/chamber#199]
we're ironing out the details of using chamber, which is working great in production. we're still tweaking local development, which right now consists of passing through `~/.aws` and/or the `AWS_*` ENV vars to allow access to Parameter Store.

we are seeing an issue where a user without proper permissions to access Parameter Store who does a `docker-compose up` sees chamber start up the app and everything looks normal, however the ENV vars are not present. debugging further, it appears `chamber list` works the same way - users with permissions can list the secrets, while users without permissions get no results without error.

- is this expected, and if so is there a way to force chamber to error out if it doesn't have permissions to access Parameter Store?
- should we be handling local development a different way, passing in ENV vars with an .env or something else? (trying to keep it as simple as possible for devs, eg not distributing secrets/.env files, etc.)

**Comment by nickatsegment** [comment]
Duplicate of or at least related to https://github.com/segmentio/chamber/issues/142?

I did post a workaround https://github.com/segmentio/chamber/issues/142#issuecomment-435548780. You could patch this into your `docker-compose.yml` entrypoint.

**Comment by hlarsen** [comment]
yep, 142 covers it.
