### ISSUE TITLE
Feature Request: chamber delete(rm) <service> or <service> <key>

### ISSUE THREAD

**Issue by sc-chad** [segmentio/chamber#20]
Basically do the opposite of write with the added functionality of deleting an entire service if applicable.

IE: `chamber delete service` would delete all keys with that namespace
or
`chamber delete service key` would delete just that specific key

Addition it will have to delete in batches of 10 due to the AWS constraint: ```Member must have length less than or equal to 10```

**Comment by jleclanche** [comment]
Seconded. Is there really no way to delete something once it's been added?

**Comment by dfuentes** [comment]
https://github.com/segmentio/chamber/pull/40 added the ability to delete individual keys via `chamber delete <key> <service>`.  Available in release v1.11.0+

**Comment by nickatsegment** [comment]
@thattomperson 	That solution looks fine to me. I would certainly accept a PR for a `delete-service` command, but it's not top priority for us atm
