### ISSUE TITLE
Cannot pull chamber image from dockerhub

### ISSUE THREAD

**Issue by johnnyplaydrums** [segmentio/chamber#207]
Hey folks! I am getting a 502 when trying to pull the chamber image:

```
$ docker pull segment/chamber:2                                                                                                                                          
2: Pulling from segment/chamber
de625255b8b7: Pulling fs layer
error pulling image configuration: received unexpected HTTP status: 502 Bad Gateway
```

Any ideas why that might be happening? Also noticing a 404 on segments dockerhub page: https://hub.docker.com/u/segment. Thanks for the help!

**Comment by johnnyplaydrums** [comment]
Andddddd now it works. Weird. Did y'all notice any issues on your end? Maybe dockerhub was having issues for a moment?

**Comment by johnnyplaydrums** [comment]
I will close out for now, if you have any context to add that'd be great but maybe it was a momentary issue with dockerhub? Thanks all 🙏

**Comment by nickatsegment** [comment]
Yeah, sounds like a dockerhub issue to me.

Re 404: Can confirm. I think our org is privately listed.

**Comment by johnnyplaydrums** [comment]
Cool, thanks!

**Comment by pedropinheiro75** [comment]
@johnnyplaydrums perhaps this issue is related to `Cloudflare` instability:
https://techcrunch.com/2019/07/02/a-cloudflare-outage-is-impacting-sites-everywhere/

**Comment by nickatsegment** [comment]
> @johnnyplaydrums perhaps this issue is related to `Cloudflare` [instability](https://techcrunch.com/2019/07/02/a-cloudflare-outage-is-impacting-sites-everywhere/).

Yeah, I was gonna guess the same, but looks like it's all AWS:

```
$ dig +short auth.docker.io registry.docker.io registry-1.docker.io | xargs whois | grep OrgName
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon.com, Inc.
OrgName:        Amazon.com, Inc.
OrgName:        Amazon Data Services NoVa
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon Technologies Inc.
```

Hard to prove or disprove.
