### ISSUE TITLE
chamber write value cannot start with `--` even with quote

### ISSUE THREAD

**Issue by eric4545** [segmentio/chamber#209]
Trying to import ssh key using chamber, but got error `Error: unknown flag: --`

## Reproduce
- `chamber write two-dash two-dash-key "--a"`
- `Error: unknown flag: --a `
- `chamber write two-dash two-dash-key '--a'`
- `Error: unknown flag: --a`

## chamber version                          
chamber 2.3.3

## Workaround
```
cat <<EOF | chamber write two-dash two-dash-key -
--a
EOF
```

**Comment by nickatsegment** [comment]
Seems like a pretty minor impact, right? 

What if the syntax were `chamber write <service> <key> [--] <value>`? So the optional `--` would allow you to be very specific? Honestly, I think the `-` workaround should just be used for all circumstances where escaping needs to happen.

**Comment by dfuentes** [comment]
That format (with `--` between key and value) should already work.  See https://github.com/segmentio/chamber/issues/27

**Comment by nickatsegment** [comment]
Well I'll be damned. Thanks @dfuentes. Added a PR to make that clearer in online help.
