### ISSUE TITLE
cli displays lowercase even though its stored in uppercase

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/chamber#21]
![image](https://user-images.githubusercontent.com/7015626/29587098-aff99ffa-8741-11e7-815b-1a26663c81b6.png)

It's confusing that the env var name is stored in uppercase but displayed in lowercase

**Comment by dfuentes** [comment]
It is stored in lower case as well.  This is to prevent people from accidentally writing two similar secrets (AUTH0_SECRET and auth0_secret), which would be ambiguous when we convert to env vars for `exec`.

**Comment by stevenmiller888** [comment]
There should at least be a message in the output indicating this. Otherwise I guarantee someone else will run into this and get confused
