### ISSUE TITLE
CHAMBER_KMS_KEY_ALIAS should support 'arn:aws:ssm:...' values

### ISSUE THREAD

**Issue by tamsky** [segmentio/chamber#212]
## Issue

If I'm writing an ssm value to `us-west-2`, but my terraform created KMS key `alias/parameter_store_key` lives in `us-east-1`, I'm unable to tell `chamber` to use a key in another region, because the `KMSKey()` function currently only checks for or prepends `alias/` prefix:

https://github.com/segmentio/chamber/blob/b55c87185fbaefb65086acf290ef1b5a7b1d8300/store/ssmstore.go#L68-L69

## Fix
Allow chamber to support cross-region KMS key_ids when `Write()`ing secrets.

## Proposed implementation:
Allow `arn:` prefixed-values in CHAMBER_KMS_KEY_ALIAS env var to be passed thru verbatim to the KeyId parameter during `Write()`:

- https://github.com/segmentio/chamber/blob/b55c87185fbaefb65086acf290ef1b5a7b1d8300/store/ssmstore.go#L89

**Comment by nickatsegment** [comment]
Sounds like a good plan. Happy to take a PR for that.
