### ISSUE TITLE
GCP Support

### ISSUE THREAD

**Issue by agolomoodysaada** [segmentio/chamber#214]
Are there plans to support GCP?

**Comment by nickatsegment** [comment]
We don't have anything on the roadmap. But besides the specific implementations of [store.Store](https://github.com/segmentio/chamber/blob/master/store/store.go#L61), I don't think there's anything else that assumes AWS (or at least there shouldn't be). Adding a new store wouldn't be a ton of work I don't think. But we at Segment probably wouldn't write it. Contributions welcome!
