### ISSUE TITLE
Proposal: integration with conf

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/chamber#215]
While `chamber exec` is a pretty common pattern at Segment, there's no reason we couldn't embed chamber as a library into Go projects. In fact, I did this once on an internal project.

The main advantage is you can configure chamber lib exactly as your binary needs it. For non-default backends (namely s3), there are a few config items that don't change, and are sometimes sources of config error.

[segmentio/conf](https://github.com/segmentio/conf) is a sane configuration loader that has some adoption around Segment. If we wrote a conf `Loader` for each backend, we could easily embed `chamber` in go projects without having to have a separate binary.

Hesitations:
- I'm not sure how good chamber is as a library. I have vague recollections of it being a little gross. That said, maybe we can isolate that complexity with this theoretical adapter.
- I'm not sure how well-adopted `conf` is at Segment, let alone externally.

**Comment by abraithwaite** [comment]
> I'm not sure how well-adopted conf is at Segment, let alone externally.

Internally, it's used extensively so would be a good target for integration.
