### ISSUE TITLE
Remove whole Service

### ISSUE THREAD

**Issue by simonireilly** [segmentio/chamber#216]
## Feature Request

I can remove an entire service using a single command:

```bash
chamber destroy <service>
```

## Feature set:

1. First forces a `chamber-export` so you can import again if you did this accidentally
2. Removes ssm parameters in batches of 10 as this seems to be the AWS limit in UI

## Example

Having created a docker image as such for developing locally:

```
FROM alpine:3.4 as final

RUN  apk update && apk upgrade \
  && apk add --no-cache ca-certificates wget \
  && update-ca-certificates

COPY . .

RUN wget https://github.com/segmentio/chamber/releases/download/v2.5.0/chamber-v2.5.0-linux-amd64 -O /bin/chamber && \
  chmod +x /bin/chamber
```

I will run an import of my local variable to share with my dev-team:

```
docker-compose -f services/chamber.yml run chamber chamber import local/credential/platform .env.platform.json
```

Having imported all these variables I want to be able to remove them aswell:

```
docker-compose -f services/chamber.yml run chamber chamber destroy local/credential/platform
```

**Comment by simonireilly** [comment]
Sorry if this has already been requests, I had a quick look, I just uploaded about 100 variables so was looking for an easy way to remove all at once :+1:

**Comment by nickatsegment** [comment]
Yep, this could be implemented for all backends. 

- Add `Store.Destroy(serviceName string)`. Or maybe a whole new interface Destroyer so we could have stores that implement some features but not others.
- Implement in each store.

I'm not 100% on the name "destroy", but that's kind of a bike shed.

**Comment by simonireilly** [comment]
Great, I'm not attached to `destroy`, just a command distinct from `remove` so you don't execute it accidentally.

I'll look to put a PR together for this :+1:

**Comment by abraithwaite** [comment]
:+1: optional separate interface for destroyer. 

Great idea!
