### ISSUE TITLE
Enhancement: history and rollback

### ISSUE THREAD

**Issue by i** [segmentio/chamber#220]
This is a proposal for versioning secrets. Required for use of this feature is the `ssm:describe-parameters` assuming it's implemented on top of the parameter-store backend. S3 support would have its own requirements but is definitely possible assuming versioning is enabled on the bucket.

Happy to take this on if it gets approved as an idea.

#### Proposed API:
```sh
# Writing a key for the first time
$ chamber write my_service db_password p@ssword123

# Overwrite the key with a new value
$ chamber write my_service db_password n3w_passw0rd456

# Overwrite the key with another new value
$ chamber write my_service db_password password1239999

# View the history for the secret: db_password
$ chamber history my_service db_password
 VERSION     VALUE            UPDATED_AT           UPDATED_BY
 1           p@ssword123      2019-03-21 10:13:01  root
 2           n3w_passw0rd456  2019-03-21 10:13:09  root
*3           password1239999  2019-03-21 10:19:21  root

# Rollback to a previous version
$ chamber rollback my_service db_password 2

# View the history again to ensure it worked. Note there's a new record
$ chamber history my_service db_password
 VERSION     VALUE            UPDATED_AT           UPDATED_BY
 1           p@ssword123      2019-03-21 10:13:01  root
 2           n3w_passw0rd456  2019-03-21 10:13:09  root
 3           password1239999  2019-03-21 10:19:21  root
*4           n3w_passw0rd456  2019-03-21 10:20:23  root

$ chamber exec my_service -- echo $DB_PASSWORD
n3w_passw0rd456
```

**Comment by i** [comment]
That's true. What are your thoughts on just implementing for ssm for the time benig since s3 is still considered experimental?

**Comment by nickatsegment** [comment]
Yep, that works for me. I would like to have a general mechanism for this sort of feature support checking (probably checked type assertions for an interface), but for now, you can feel free to just do something simple and explicit like `if backend != BackendSSM { ... `

**Comment by eculver** [comment]
Fun fact: the `Store` interface already includes a `History` method: https://github.com/segmentio/chamber/blob/master/store/store.go#L67

(which not all backends fully implement)

I'm wondering if this was the intention all along? Perhaps all we're really missing is `Rollback`?

**Comment by nickatsegment** [comment]
Yep I think the intention was there for at least an audit trail.

**Comment by i** [comment]
Sorry yeah, that's exactly what's left. I didn't realize there was already a history command built in to the CLI. Rollback is what remains. Does the interface proposed above seem appropriate? If so, I can submit a PR in the next couple days.

**Comment by nickatsegment** [comment]
Wouldn't `Rollback` be the same for all stores? Roughly `Write(GetVersion(currentVersion-1))`?

**Comment by i** [comment]
@nickatsegment yep. That's cool you can read specific versions. I hadn't seen that feature before.
