### ISSUE TITLE
Feature Request: `find` command

### ISSUE THREAD

**Issue by AaronME** [segmentio/chamber#221]
In our env we have inherited a large number of services with keys duplicated throughout. Naming conventions are inconsistent. We found it useful to add a `find` command in chamber which helps us search across services for matching keys. We also implemented a flag which allows us to find keys by value, helping us locate dependencies on common resources across many services.

We believe this investigative feature would be useful to others.

```
$ chamber find -h
Find the given secret across all services

Usage:
  chamber find <secret> [flags]

Flags:
  -v, --by-value   Find parameters by value
  -h, --help       help for find
```
```
$ chamber find s3_bucket_name
Service
service1
service2
service5
```
```
$ chamber find s3://this_bucket --by-value
Service				Key
service1			s3_bucket_name
service2			s3_bucket_name
service3			s3_bucket
service4			s3_bucket_base
service5			s3_bucket_name
```

**Comment by nickatsegment** [comment]
> Would be nice to support all the various backends.

I just realized your example wasn't using `s3://this_bucket` as a backend as I had assumed. Rather as a value. My bad.
