### ISSUE TITLE
Request: Add `--recursive` feature to `export` cmd

### ISSUE THREAD

**Issue by jimbocoder** [segmentio/chamber#225]
`chamber` is really helpful as an administrative tool, but makes it difficult to pull down a larger, deeper parameter tree for consumption by applications.

If this is in line with design goals for the tool, it would be as simple as adding support for the "recursive" option to the `GetParametersByPath` calls.

Thanks!

**Comment by nickatsegment** [comment]
Hm, I'm not sure what "recursive" would mean in terms of chamber's model. Especially considering other backends. Can you give me an example of what your hierarchy looks like?

**Comment by jimbocoder** [comment]
@nickatsegment This is the type of hierarchy we are trying to use with `chamber`:

```
└── prod
    └── my-project
        └── dbs
            ├── django-db
            │   ├── credentials
            │   │   └── default
            │   │       ├── password
            │   │       └── username
            │   ├── default-db
            │   ├── engine
            │   ├── host
            │   └── port
            │   └── url
            └── warehouse-db
                ├── credentials
                │   └── default
                │       ├── password
                │       └── username
                ├── default-db
                ├── engine
                ├── host
                └── port
```

The idea being that an app could export the entire `prod/my-project` service as "deep" JSON. Another more limited warehousing app might only export the `prod/my-project/dbs/warehouse-db` service as more "deep" JSON.

Because `chamber export` doesn't allow recursion, you can only export the direct leaves (*ie.* children, but not grandchildren) for a given service. Basically, it seems like `chamber` forces a service to have a flat hierarchy, because `/` is not allowed in key names. It would be really helpful to export more flexibly.

My understanding of `chamber` is that the "service" concept is really just an SSM prefix, so putting restrictions on the key names to force a flat hierarchy is currently causing me pain (or is it just confusion? ;))

I confess: this would introduce a wrinkle when recursively exporting a deep tree to one of the other supported, non-hierchical formats, like `CSV` or `dotenv`. Some key-flattening agreement would have to be adopted for predictable results.

Alternatively, skip that concern and only allow `--recursive` on backends and formats that can handle it, like `json` and `tfvars`. In that case, I think this is a relatively simple feature.

Appreciate any further thoughts you or others may have. Maybe we're just using chamber wrong and it's not the right tool for us.

**Comment by jimbocoder** [comment]
Thanks for all your feedback on this. I think you're right, as we're not using `chamber exec` we're just trying to use the tool in ways counter to its design.

Closing!
