### ISSUE TITLE
docs: Update Changelog

### ISSUE THREAD

**Issue by tomciopp** [segmentio/chamber#233]
There have been a few releases but unfortunately there have been no additions to the changelog in a while. Can you update the changelog with any features or breaking changes people downstream might have to deal with?

**Comment by nickatsegment** [comment]
Sorry. Maintaining CHANGELOG.md is a thankless chore and writing back to the repo from CI seems dirty to me, so I've automated the changelogs in the github releases so they should be more accurate, and replaced CHANGELOG.md with a reference to there.
