### ISSUE TITLE
Graceful fail option

### ISSUE THREAD

**Issue by IVBakker** [segmentio/chamber#237]
For local development where I don't have SSM param access at all I would like to provide an option that would let chamber to gracefully fail and simply use the environment variables passed in the first place:
Instead of:
```
docker run -it alpine_chamber exec toto -- env
Error: Failed to list store contents: MissingRegion: could not find region configuration
```
I would like to have:
```
docker run -e ABC=ABC alpine_chamber exec toto --nofail -- env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=31454062a16b
ABC=ABC 
HOME=/root
```

BONUS: the SSM checks look to take quite some time, a shorter timeout would be better.

Note: here is the content of my alpine_chamber image:
```
FROM alpine AS run

COPY --from=segment/chamber:2.7.2 /chamber /chamber

ENTRYPOINT ["/chamber"]

```

**Comment by nickatsegment** [comment]
Would `chamber -b null` work here?
