### ISSUE TITLE
chamber exec command fails to inject environment variables into command

### ISSUE THREAD

**Issue by minademian** [segmentio/chamber#239]
Hi, the client is running v2.3.2 with this command `chamber exec <service> -- yarn start-log` in a script file that is executed at the end of the Docker image creation. The stack is CircleCI, AWS Elastic Beanstalk, node, and TypeORM.

I expect the database environment variables to be set in the resulting Docker image.

When the entire CI build is complete and I SSH into the Docker image, I see that the secrets have not been passed into the yarn command.

Are there any known and undocumented issues with chamber and yarn? I can't find any related issues here or online in general.

**Comment by eculver** [comment]
If I had to guess without seeing your CI or yarn config, you probably need to tell Docker which environment variables to pass into the container. If chamber isn’t exiting non-zero, I would suspect something is happening after its invocation that is dropping the values. You can test this by writing a yarn target that executes `env` and doing `chamber exec <service> — yarn run env` to see the values being used by the yarn target.

**Comment by minademian** [comment]
Thanks for responding.

Alright, I will try that out in the CI file. Great suggestion!

This is a redacted version of the Dockerfile:
```
FROM node:10-alpine

RUN apk add --no-cache curl
RUN apk add --no-cache python make g++

COPY scripts/install-chamber.sh /usr/local/bin/
RUN /usr/local/bin/install-chamber.sh
-- snip ---

RUN mkdir -p /opt/app
WORKDIR /opt/app

ARG APP_VERSION
ENV APP_VERSION $APP_VERSION
ARG ENVIRONMENT
ENV ENVIRONMENT $ENVIRONMENT
ENV PORT 8080
EXPOSE ${PORT}

--- snip ---

COPY scripts/run.sh run.sh
RUN chmod +x run.sh
--- snip ---
COPY package.json .
COPY src src
COPY dist dist
RUN yarn install

CMD ["./run.sh"]
```

... and this is the `run.sh` shell script:
```
#!/usr/bin/env sh

chamber exec <service>-"$ENVIRONMENT" -- yarn start
```

**Comment by minademian** [comment]
> If I had to guess without seeing your CI or yarn config, you probably need to tell Docker which environment variables to pass into the container. If chamber isn’t exiting non-zero, I would suspect something is happening after its invocation that is dropping the values. You can test this by writing a yarn target that executes `env` and doing `chamber exec <service> — yarn env` to see the values being used by the yarn target.

hey @eculver. I noted this in the log:
```
Done in 0.04s.
warning: service <> overwriting environment variable DBNAME
```

**Comment by eculver** [comment]
To me, that looks like chamber is working. Can I assume that you were able to see the values elsewhere in the log? The only other component to this is how Docker is being invoked. If it's only in CircleCI that you're not seeing the values, this documentation might help: https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-container. You can test locally by doing something like:

```
docker build -t service .
chamber exec <service> -- docker run -e DBNAME service
```

I hope this helps.

**Comment by eculver** [comment]
I'm going to go ahead and close this. If there are further issues feel free to re-open.
