### ISSUE TITLE
no packages for EL6

### ISSUE THREAD

**Issue by in4mer** [segmentio/chamber#243]
Hi,

The package listing for EL6 is empty.  I'm following the setup for packagecloud.io and it is nonfunctional.  Is this a recent development?

**Comment by in4mer** [comment]
Ah, ok ): I guess I saw the EL6 (amazon linux) setup in packagecloud.io and got excited.  I guess it's back to storing the binary in s3.  Any chance for an el6 RPM in the future?

**Comment by nickatsegment** [comment]
Unlikely I'm afraid. I bet the Fedora RPMs would work fine on EL; it's just a binary going into `/usr/bin`. It's just the repo that isn't compatible

**Comment by in4mer** [comment]
I'll try to add one and see.  Shall I let you know if it works?

**Comment by in4mer** [comment]
I'll try to add one and see.  Shall I let you know if it works?

Couldn't get the repo to work ): RPM's good, though!  I'm going to write (yet another) installer using Chef, thank you for the quick response!
