### ISSUE TITLE
Does not work with services or secrets that already exist in ParameterStore as UPPER CASE

### ISSUE THREAD

**Issue by mschnee** [segmentio/chamber#248]
When there are existing secrets in Parameter Store, `chamber` cannot be used to access them at all because of the following:
```go
        if len(args) == 0 {
		service = ""
	} else {
		service = strings.ToLower(args[0])

	}
```
So, keys that already exist in SSM, such as `/ORGNAME/ENVIRONMENT/APP_NAME/MY_ENV_VAR`, cannot be listed, viewed, or read.

Please make this behavior optional.

**Comment by felipeTaps** [comment]
This also affects secrets that were imported via a json file and have an all caps key. 

<img width="1142" alt="Screen Shot 2020-03-06 at 11 07 23 AM" src="https://user-images.githubusercontent.com/42149663/76100691-18de1a80-5f9b-11ea-9ee4-22f89ef325b5.png">

**Comment by Gowiem** [comment]
Yeah, this seems like a bug to me. Enforcing our SSM parameter keys are stored in a particular format (whether uppercase or lowercase) seems like a decision that chamber shouldn't care about and certainly shouldn't not work because of.

**Comment by Gowiem** [comment]
@dfuentes @nickatsegment Apologies for the direct ping, but saw you two were the top contributors. 

I'd be interested in contributing to fix / improve this. I saw in ya'lls CONTRIBUTING.md that you folks are big about discussing work before putting up a PR, so wondering if you would be interested in this fix or would like to discuss it at least? Let me know your thoughts, thanks gents!

**Comment by nickatsegment** [comment]
This is part of a bigger design problem. There's snippets of info scattered around existing issues and PRs, so I created #251 to corral them.
