### ISSUE TITLE
Actual use on ECS

### ISSUE THREAD

**Issue by joeunrue** [segmentio/chamber#250]
So I'm sorry in advance for a) asking a dumb question and b) if this is not the place for asking questions, but: I have my keys in Parameter Store using chamber, but what now? Chamber seems great for getting environment variables locally but what is the process for getting this to work on production in a docker container on ECS? I've seen a post once place talking about using the startup command in Docker to load the variables in that way, but is there an example of a Dockerfile someone could point me to that shows how chamber gets installed? And then would you need to do something with access/secret keys to read the parameters on the container?

Thanks!

**Comment by rh-kpatel4** [comment]
`CMD ["chamber", "exec", "config/prod/web", "--", "node", "--harmony", "--max_old_space_size=8192", "/opt/wsbx/app.js"]`

**Comment by nickatsegment** [comment]
I've got an example for how to install chamber [in my original Dockerfile PR](https://github.com/segmentio/chamber/pull/186#issue-251237835):

```
FROM segment/chamber:2 AS chamber
FROM scratch

COPY --from=chamber /chamber /bin/chamber

COPY ./myapp /bin/myapp

ENTRYPOINT ["/bin/chamber", "exec", "myapp", "--", "/bin/myapp"]
```

**Comment by joeunrue** [comment]
so if I already have a Dockerfile for my app I can just add 

```
FROM segment/chamber:2 AS chamber
COPY --from=chamber /chamber /bin/chamber
```

to the top? And then the entry point down at the bottom?

`ENTRYPOINT ["/bin/chamber", "exec", "myapp", "--", "/bin/myapp"]`

And chamber will just work without setting up credentials?

**Comment by nickatsegment** [comment]
Well you need to make sure the role ECS runs your container (in your task definition) as has permissions to access SSM. ecs-agent injects the role creds for you.

**Comment by joeunrue** [comment]
Thanks Nick! I did get everything working, and if it helps the next person to find this here are my IAM policies:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:ListKeys",
                "kms:DescribeCustomKeyStores",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Describe*"
            ],
            "Resource": "arn:aws:kms:us-east-1:<accountKey>:key/<resourceId>"
        }
    ]
}
```
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ssm:GetParametersByPath",
                "ssm:GetParameters",
                "ssm:GetParameter"
            ],
            "Resource": [
                "arn:aws:ssm:us-east-1:<accountKey>:parameter/path/for/keys",
                "arn:aws:ssm:us-east-1:<accountKey>:parameter/path/for/keys/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "ssm:DescribeParameters",
            "Resource": "*"
        }
    ]
}
```

I slapped these two custom policies and the AWS AmazonECSTaskExecutionRolePolicy policy onto a new role and made that the task execution role for the ECS task and it works!

And also I just wound up adding 
```
RUN curl -s https://packagecloud.io/install/repositories/segment/chamber/script.deb.sh | bash
RUN apt-get install -y chamber
```
to my Dockerfile. I'm sure there's a better way to do it but that works.
