### ISSUE TITLE
feature request: case (in)sensitivity and custom service name formats

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/chamber#251]
Chamber is designed to read and write secrets only in its own format; it does not aim to be an injector of arbitrary SSM values.

That said, there's a clear desire for such abilities:

- https://github.com/segmentio/chamber/issues/248
- https://github.com/segmentio/chamber/issues/160
- ...

The chamber normalization rules are not really , but roughly means `lowercase-with-hyphens` in storage (`chamber write`) and `UPPERCASE_WITH_UNDERSCORES` in the environment (`chamber exec`).

Adding these features would probably require:
- API changes to the `Provider` interface and/or options to `Provider` implementors. We need to ensure this is implemented consistently across `Provider`s
- CLI flags to ensure we retain current behaviour while allowing for exceptions

**Comment by nickatsegment** [comment]
Honestly this is so fundamental to chamber's design that it's almost worth forking it. I wan't `chamber exec` to be tight and straightforward, not have a bunch of "whoops, I broke prod" flags.

**Comment by Gowiem** [comment]
@nickatsegment Ah gotcha this is a bigger change than I originally thought. 

That being said, I would suggest attempting this as I'm sure this would be a blocker for other teams who have already adopted SSM (or other providers) and are looking to add chamber to their process. 

I personally believe you can separate out the `chamber exec` change as I can't imagine wanting to consume environment variables in anything other than the standard `UPPERCASE_WITH_UNDERSCORES` format. IMHO it's purely the format of the param names provided in `write` and `read` which shouldn't be forced to conform to such a specific format. Obviously forking this tool to provide that would be a shame. 

If you want to carve this up I'd still be happy to take a crack at trying to implement this if I can find the time. 

Thanks!

**Comment by nickatsegment** [comment]
It sounds like you're looking for a general purpose SSM CLI, in which case I have to ask, why not just use the AWS CLI?

(FWIW, I believe import and export *don't* change case, so that might give you a workaround.)

**Comment by Gowiem** [comment]
@nickatsegment Yeah, that's a reasonable thing to bring up and I definitely could use the AWS CLI to read those parameters. My only point against that is if I'm using Chamber for managing my application's access to SSM Parameters then I'd like to use it over the AWS CLI to drive overall tool consistency within my team. 

Basically, I'd like to avoid this question from my team: "Hey I saw we're using Chamber to provide environment variables to the application, but when I go to read any of those environment variables locally using that tool it says they cannot be found. What's up with that?". I could tell that team member to use the AWS CLI when doing any read or write interactions with SSM Params, but that just seems disjointed.

**Comment by in4mer** [comment]
I'd like to boop this to re-open..  Given the rather expanded list of export formats now available, I think the ability to retain case sensitivity and WYSIWYG between chamber<->ssm is pretty self evident.  I can see how chamber is designed to be a shell interface, and it's quite nifty for that, and as such I would expect the case-mangling to occur when using `exec` or `env`.  But not when using `write`.

**Comment by Gowiem** [comment]
Three years later and this issue has bitten me again on a different project. Wish this one had seen some life!
