### ISSUE TITLE
Version mistmatch between linux and macOS

### ISSUE THREAD

**Issue by chrisgilmerproj** [segmentio/chamber#253]
I'm trying to determine the best place to open this issue. When I run `chamber version` I get different values. 

macOS with homebrew:

```
$ chamber version
chamber 2.8.1
```

linux from downloaded release binary:

```
$ chamber version
chamber v2.8.1
```

I think the problem is here: 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/chamber.rb#L18

Specifically:

```
system "go", "build", "-ldflags", "-s -w -X main.Version=#{version}", "-trimpath", "-o", bin/"chamber"
```

should add a `v` :

```
system "go", "build", "-ldflags", "-s -w -X main.Version=v#{version}", "-trimpath", "-o", bin/"chamber"
```

Is this correct? And would you like a PR in the other repo? Do you control that?

**Comment by chrisgilmerproj** [comment]
I verified this was the issue with these tests:

```
$ go build -ldflags "-s -w -X main.Version=v2.8.1" -trimpath -o bin/chamber
$ ./bin/chamber version
chamber v2.8.1
$ go build -ldflags "-s -w -X main.Version=2.8.1" -trimpath -o bin/chamber
$ ./bin/chamber version
chamber 2.8.1
```

**Comment by chrisgilmerproj** [comment]
I opened a PR to solve this issue. Hopefully when it gets merged we can close this out.

**Comment by nickatsegment** [comment]
yeah, we pass through the result of `git describe` to that linker flag, which should just be the tag, which includes `v`. I'm not really sure where their magic `version` variable comes from, but looks like it's a pure semver version without the `v` prefix

**Comment by chrisgilmerproj** [comment]
I think that it's an internal version value from Brew. So in that case hopefully my fix is all it needed.
