### ISSUE TITLE
[enhancement idea] Ability to choose whether to overwrite existing keys when importing

### ISSUE THREAD

**Issue by caleb15** [segmentio/chamber#255]
We have certain keys controlled by terraform that we do not want to be overwritten. Adding the ability to skip existing keys when importing would be useful to us and probably others as well.

As a workaround we used chamber read to check is the secret exists already and chamber write to write the secret.

```shell
    if chamber read -q "${VPC_NAME}/${SECRET_PATH}" "${KEY}" > /dev/null 2>&1; then
      echo "${VPC_NAME}/${SECRET_PATH}" "${KEY}" already exists
    else
      echo "chamber write '${VPC_NAME}/${SECRET_PATH}' '${KEY}' --> ${VALUE}"
      # use print to send value to chamber without newline
      # we pass value in via stdin because if we do arguments
      # bash might expand "foo foo" as two different arguments even though they are just one
      # Also we do %s so printf echoes argument verbatim
      printf -- '%s' "$VALUE" | chamber write -- "${VPC_NAME}/${SECRET_PATH}" "${KEY}" -
    fi
```

**Comment by nickatsegment** [comment]
Are you talking about the literal `import` command, or `write` as well?

Can you mock up what the CLI would look like?

**Comment by caleb15** [comment]
I'm talking about import. 

Something like this. `chamber import service file --skip-existing`

**Comment by caleb15** [comment]
@nickatsegment can this be marked as a enhancement please?

**Comment by caleb15** [comment]
Ah, that wouldn't help the stale label. Nevermind I suppose.

**Comment by caleb15** [comment]
Just ran into a scenario again where this enhancement would be have been really nice. @rikez would you be open to a PR for this? I might get time during a company hackathon.
