### ISSUE TITLE
Docs: Correct directions for terminal env vars

### ISSUE THREAD

**Issue by Nuru** [segmentio/chamber#259]
The directions for setting env vars in your terminal given in #247 are wrong. 

https://github.com/segmentio/chamber/blob/c2a053008714ca9c1aede3e1a804ae5764cb96b7/README.md#L174-L178

This does not work correctly with various special characters. In general, use of the `dotenv` format should be avoided (see #208), and especially here when we have #184 specifically to handle this use case. 

Recommended change:

To set env vars in your terminal you can use the `chamber env` command. For example, 
```shell
source <(chamber env service)`
printf "%s" "$SERVICE_VAR"
```

**Comment by nickatsegment** [comment]
SGTM. Wanna make a PR?

**Comment by Nuru** [comment]
@nickatsegment I'd rather not spend time on the whole fork and PR thing, if you don't mind, and I don't need attribution. Please just go ahead and fix it in your next update.
