### ISSUE TITLE
aws-sdk-go too old for credential_process support

### ISSUE THREAD

**Issue by frimik** [segmentio/chamber#264]
If your aws profile uses a credential process, you might get this failure:

```sh
Error: Failed to list store contents: ProcessProviderParseError: parse failed of credential_process output
```

Fixed in https://github.com/aws/aws-sdk-go/releases/tag/v1.25.42 by https://github.com/aws/aws-sdk-go/issues/2875

Compiled *chamber* locally against `aws-sdk-go v1.31.1` which seems to work ok for my purposes but beyond that haven't verified it much. Dropping this issue here for now.

**Comment by dhess** [comment]
I've just run into this as well. Can this issue be re-opened, please?
