### ISSUE TITLE
bug: chamber write unable to write value that begin with -- 

### ISSUE THREAD

**Issue by nsfmc** [segmentio/chamber#27]
chamber will attempt to treat the value (i.e. an RSA key) into a command line parameter. you can manually create a well formed parameter with the AWS cli so chamber can read it later, but chamber can't import a `---` prefixed parameter.

sorry, i don't have any go programming smarts, otherwise i would attempt a patch for this that allows passing in the secret via stdin or somesuch. thanks!

**Comment by dfuentes** [comment]
Thanks for the report!  I agree that we should allow reading from stdin (I've opened a new issue here to track https://github.com/segmentio/chamber/issues/28).

For your specific use case, you should be able to write your secret like:
`chamber write <service> <key> -- <value>`, notice the `--` between key and value.  This double dash tells the flag parser to stop looking for optional flags.  Let me know if this works for you.

**Comment by nsfmc** [comment]
totally worked, thank you

**Comment by dfuentes** [comment]
No prob, glad it worked out
