### ISSUE TITLE
Question: rate limit concern?

### ISSUE THREAD

**Issue by johnnyplaydrums** [segmentio/chamber#275]
Hey folks - I wasn't sure where else to ask this questions so please feel free to direct me to the correct forum if this isn't the place.

We've been using chamber in production for a while and it's been working wonderfully. Thanks for creating and open-sourcing this awesome project 🙌 . We're considering adding chamber to a bunch of new services with new engineers using it locally as well and worried about the API throttling from AWS. I've enabled higher throughput, and so I believe the bottleneck would be the 100 rps limit on `GetParametersByPath`, as described in the Service Quotas section in [these AWS docs](https://docs.aws.amazon.com/general/latest/gr/ssm.html). Is there another API call to be concerned with or would `GetParametersByPath` indeed be the bottleneck? `chamber exec` is the only command we would be using a lot.

In production with ~20 services and about ~20 engineers also using it locally, have folks with a similar footprint run into AWS API rate limits? 100 RPS seems like it would get us pretty far so I'm not sure if we should be concerned with hitting rate limits. And with exponential backoffs in place, both within chamber / aws golang and within our container orchestrator, seems like we'd be ok even in the event of a huge API spike. I'm just wondering what folks have seen in the wild with large chamber deployments. Thanks!

**Comment by nickatsegment** [comment]
Yep, we were hitting those rate limits during any "thundering herd" event. The s3 backend was invented specifically to work around that. We didn't switch wholesale, just the services which tended to do the damage.

**Comment by johnnyplaydrums** [comment]
Gotcha, yeah I was eyeing the s3 backend as a backup solution if we start hitting rate limits. Have you been using it in production without major issue? I see the disclaimer about not using it in production, but I take it y'all are using it in production?

**Comment by johnnyplaydrums** [comment]
Thanks for the feedback Nick, I'll close this out but feel free to chime in on how it's been using the s3 backend, and if you would consider it production ready yet. Thank you!

**Comment by nickatsegment** [comment]
@johnnyplaydrums Yes, we're using it in production. I think the main reason we don't want to commit to stability yet is that the storage format is a bit hacky and it'd be hard to guarantee backwards compatibility if we need to change it.
