### ISSUE TITLE
what format is the macos binary in?

### ISSUE THREAD

**Issue by vomc** [segmentio/chamber#276]
just a quick question: i am looking to install chamber on my mac and dont want to go through the pain of setting up go, so I am looking at the pre-built binaries but when I try to download this it is saying the format is '2-DARWIN-AMD64 File' ... (see image below)

<img width="381" alt="Screenshot 2020-07-08 at 09 54 10" src="https://user-images.githubusercontent.com/78635/86892802-06b6e900-c101-11ea-9076-0132ed5aea43.png">

I have tried renaming to `dmg` and also ´zip´ but this is not working. Any ideas?

**Comment by vomc** [comment]
nm, installed it through homebrew

**Comment by nickatsegment** [comment]
They're just the binary, no zip or anything. I don't think that Format drop down will have any effect.

**Comment by rafalp** [comment]
Rename file to `chamber` and then make it executable with `chmod +x chamber` and it will work.
