### ISSUE TITLE
doc: misleading import/export documentation

### ISSUE THREAD

**Issue by mtmn** [segmentio/chamber#279]
Hi all,
https://github.com/segmentio/chamber/pull/265 has been merged to master, however latest release does not have this functionality as it was built few days prior to above PR.

However, https://github.com/segmentio/chamber#exporting already contains `yaml` as a supported format.

**Comment by nickatsegment** [comment]
Hm, it's hard to make this obvious without a proper versioned doc system outside of READMEs, but you should consider [the README on the tag corresponding to your version](https://github.com/segmentio/chamber/tree/v2.8.2#exporting) as canonical. The README you're referring to is for master, which may not have had a release.

That said, we should cut a release :)
