### ISSUE TITLE
Support writing secret values from stdin

### ISSUE THREAD

**Issue by dfuentes** [segmentio/chamber#28]
It would be nice to be able to write secrets using stdin, for example if you wanted to take file contents and write that as a secret with `cat foo | chamber write service key`.

**Comment by osterman** [comment]
For anyone else curious, it appears chamber supports reading values from `stdin`, although this issue does not mention it. I tried the following and it works:

```
chamber write app version - < /etc/alpine-release
```

**Comment by dfuentes** [comment]
Yeah, this ticket was closed when that support was added.  It's in the readme (https://github.com/segmentio/chamber#writing-secrets), but is not very well explained in the online help `chamber help write`.
