### ISSUE TITLE
How much longer will the S3 backend be experimental?

### ISSUE THREAD

**Issue by epicserve** [segmentio/chamber#280]
First of all, thank you for this open-source software! I use it for our application for my full-time job and it works great.

I would like to use Chamber for my personal projects and use the S3 backend, but it says not to use it in production. So I was wondering when it would be out of the experimental stage. I would use the default KMS service but the pricing is confusing and I'm not sure how much that will add to my personal AWS bill.

**Comment by nickatsegment** [comment]
Honestly, we at Segment have been using it in production for at least a year with no issues.

My main reluctance in committing to being production-ready for the broader OSS community is around the storage format on top of S3 and longer-term compatibility and maintainability. Namely, if we need to change the format, can we make that transition smoothly? The transition from SSM `/`-based paths was pretty rocky and I wouldn't want to repeat it :)

Anyway, if you're good with that caveat, it's probably good to use in production.

**Comment by epicserve** [comment]
So if I'm understanding you correctly, I can use it, but changes in the future could break it. Is that correct? I don't know if you're using JSON, but is it not possible to have a migration script of some kind? Or that is possible and you just don't know if you want to commit yet to creating one for releases that have breaking changes?

**Comment by nickatsegment** [comment]
Yep, it's JSON, and a migration tool would be 100% possible (in fact, I'd consider it a requirement). We just don't have much of a strategy in place for "versioned" backends, so I'm not sure what that migration would look like. Worst case, I'd say you'd have to write something that transforms the old format to the new.

**Comment by nickatsegment** [comment]
> So if I'm understanding you correctly, I can use it, but changes in the future could break it

Potentially. But you could just stick to an old version. And honestly, there aren't any planned changes to it in the future.
