### ISSUE TITLE
Chamber write does not normalize key like description says when written

### ISSUE THREAD

**Issue by ovalenzuela19** [segmentio/chamber#281]
Normalization according to Chamber docs follows:
_Secret keys are normalized automatically. The - will be _ and the letters will be converted to upper case (for example a secret with key secret_key and secret-key will become SECRET_KEY)._

However:
`chamber write my-service dummy-key dummy_value` writes the key as `dummy-key` instead of `DUMMY_KEY` when checking value in AWS. Also normalizes `DUMMY_KEY` to `dummy_key`

**Comment by nickatsegment** [comment]
That is a little confusing. What it means is that on write, keys are normalized to `lowercase-with-dashes` form (e.g., when writing to parameter store), and that on read (`read` or `exec`), they are normalized to `UPPERCASE_WITH_UNDERSCORES` form.

Some more context on why that is the case: https://github.com/segmentio/chamber/pull/238#issuecomment-572221781
