### ISSUE TITLE
`2.9.1-ci2` release tag question

### ISSUE THREAD

**Issue by chenrui333** [segmentio/chamber#291]
👋  it looks like the latest release is `2.9.1-ci2`, is there any documentation about the release semantics to help interpret the stability of the releases? Thanks!

**Comment by nickatsegment** [comment]
My bad! That was testing a CI config change. We use semver, so `-ci2` should be considered a prerelease. The `prerelease` flag on Github Releases didn't get set properly. I've fixed that manually.

I also just released v2.9.1 proper, building now.

**Comment by chenrui333** [comment]
I see, make sense, thanks for the quick fix. 👍
