### ISSUE TITLE
Support tagging of created resources

### ISSUE THREAD

**Issue by Aresius423** [segmentio/chamber#297]
Hi,

I needed tags on all the SSM parameters that chamber created in my AWS account, so I added support for a --tags-file \<path\> flag on my fork.
Do you think this would be worth merging if I tidied it up and implemented it for the other stores?

Thanks,
Janos

**Comment by nickatsegment** [comment]
hey Janos, there was some interest in https://github.com/segmentio/chamber/issues/89 but it went stale.

What does a tags file look like? I feel like `--tag <blah> --tag <blah2>` would be simpler?

**Comment by Aresius423** [comment]
The tags file is a simple map[string]string of tag keys and values.
I have multiple tags files committed into my repository that my pipeline uses to update a few chamber environments. Only supporting `--tag <blah>` style tags would mean having to repeat them with each command in the buildspec file, or doing some jq magic.

I do see the merit in that though, and it wouldn't be all that difficult to add support for both styles, so I'll do that too. Argument tags overriding tags from the file would be reasonable, I think.
