### ISSUE TITLE
Feature: chamberrc file to facilitate developer workflow automation

### ISSUE THREAD

**Issue by xeger** [segmentio/chamber#300]
The use case I'm targeting is a fleet of services running on my laptop (e.g. in Docker Compose or k8s) where the container orchestrator reads the services' secrets from `.env` files on disk. In my project, the secret-full env files are added to `.gitignore` and I use chamber to write fresh secrets to the files before turning up the containers to do some development.

Secrets can become stale over time; I wanted a one-shot command that will freshen all of my `.env` files. Initially, this was a script in my project; developers can run `bin/setup` which invokes `chamber export -f dotenv` several times, one for each service that needs to be exported to file.

I copied this pattern to a couple more projects, and eventually generalized it so that the setup script takes its instructions from a `.chamberrc` macro file rather than hardcoding calls to the `chamber` binary. The chamberrc is really just a recipe for a sequence of chamber invocations + the flags for each, e.g.

```
export -f dotenv -o service1.yml service1
export -f dotenv -o service2.yml service2
```

The setup script iterates over the lines of this file and feeds each to `chamber`, and all the files are written. My power users have written shell functions to parse and execute the RC file whenever they chdir into a directory that's got a `.chamberrc` so that secrets are freshened automatically.  I'm also exploring support for `chamber env` to automate exports to the shell environment for more sensitive (production mode) secrets that I don't want written to file -- although, of course, the chamber binary can't do this itself; some eval from the shell function is required.

Anyhow: this issue is a proposal to move support for the `.chamberrc` file into Chamber itself, on the chance it might be useful to others. I'm happy to do the development work on this if you're interested. I can think of a few implementation options, which we can discuss if the maintainers think the basic feature would be useful to others.

**Comment by nickatsegment** [comment]
Hm, I think that seems too workflow-specific to be included in chamber itself. Sorry. If you want to make the tool in a separate repo, I'd be happy to plug it from the README.

Not to invalidate your use case, but you should be able to do `chamber exec blah -- docker-compose up` and have the secrets trickle through.

**Comment by xeger** [comment]
`chamber exec` is fine for a single-service scenario, but with Compose (or a k8s deployment, etc) you're almost certainly dealing with multiple services, some of whose secrets might have colliding names; it's necessary to write the secrets to files vs. passing them through the orchestration tool's env.

I'll implement this tool as a shell function and whip up some tests, then ping you. Cheers.

**Comment by nickatsegment** [comment]
In that case, you could pass through some AWS creds and run chamber in the containers.

**Comment by xeger** [comment]
Tempting though it is, we've hit rate-limiting using SSM + KMS and of course, this rate limiting has a pretty catastrophic outcome (pods never become healthy, CI jobs fail, etc). We've taken to "spooling" secrets to the k8s secret store, or for developer/CI scenarios, to git-ignored dotenv files on disk. This lowers the rate enough to avoid AWS' ire and localizes the failure domain -- once a new deployment is up within a cluster, failures in the AWS service won't impact any operations.

No doubt there are better choices of chamber backend than SSM, but the spooling effort is behind us by now and we don't feel any pain with the status quo.

**Comment by nickatsegment** [comment]
Yeah, absolutely. For a few of our high-churn services, we switched to the S3 backend. Not fun logistically.

Brain idea: maybe a local chamber cache is the solution? That's essentially what you're doing I guess.

**Comment by xeger** [comment]
Indeed; but a more general cache or reverse proxy would be a more broadly
useful solution than what I've done. I'll keep it in my back pocket unless
we need to elaborate. Thanks for the ideas (and for the indispensible tool!)
