### ISSUE TITLE
Secretmanager backend can loose history when updating or adding keys

### ISSUE THREAD

**Issue by haddowg** [segmentio/chamber#301]
@danmactough first of thanks for adding secretmanager support, but think i have found a small issue.

when writing a key the version used to set the `CHAMBER{N}` stage tag is derived from the metadata version for that one key rather than the latest version amongst all keys.
As such updating a key with an older version than the latest or adding a new key will result in overwriting an exiting `CHAMBER{N}` stage and some history is lost as a result.

to reproduce create a new secret with a key and then modify its value so that version is 2
```
chamber -b secretsmanager write example key1 value1
chamber -b secretsmanager write example key1 value2
chamber -b secretsmanager history example key1
Event		Version		Date			User
Created		1		2021-04-15 09:57:47	...
Updated		2		2021-04-15 09:58:05	...
```
add a new key (or modify a key whos version is still 1) and view history of the previous key
```
chamber -b secretsmanager write example key2 value1
chamber -b secretsmanager history example key1
Event		Version		Date			User
Updated		2		2021-04-15 09:58:05	...

chamber -b secretsmanager history example key2
Event		Version		Date			User
Created		1		2021-04-15 10:02:34.    ...
```
history is lost :( since CHAMBER1 tagged to the new version

**Comment by danmactough** [comment]
@haddowg Great bug report and explanation of what logic is causing the bug. Want to submit a PR?

**Comment by haddowg** [comment]
Go is not my first language but may give it a go if I get some free time 😉

**Comment by danmactough** [comment]
> Go is not my first language

Nor mine! 😀  If you put up an in-progress PR and ask for help, I can help.
