### ISSUE TITLE
Unable to locate package chamber (debian, docker)

### ISSUE THREAD

**Issue by andrewcstewart** [segmentio/chamber#315]
I'm suddenly getting the following during a docker build:

```
E: Unable to locate package chamber
The command '/bin/sh -c curl -s https://packagecloud.io/install/repositories/segment/chamber/script.deb.sh | /bin/bash     && apt-get install -y chamber' returned a non-zero code: 100
```

I'm guessing this is something related to debin eol, etc..  Is there a preferred installation route for docker images that would be more stable to that?

**Comment by asaf-erlich** [comment]
@andrewcstewart in order to reproduce this error should I run the command you provided above?
``` 
/bin/sh -c curl -s https://packagecloud.io/install/repositories/segment/chamber/script.deb.sh
```
?

**Comment by asaf-erlich** [comment]
That doesn't work on my mac 🤦  of course. Can you include reproducible steps? I assume this is an ubuntu machine? As soon as I can reproduce I'll create a backlog ticket for us to fix this.

**Comment by andrewcstewart** [comment]
It was in a Docker image sourcing `python:3.6`.

But actually I just figured out how to use https://github.com/segmentio/chamber/wiki/Installation#from-a-docker-image directly in my own image, which works great.

**Comment by asaf-erlich** [comment]
Great, alright if I close this issue then?

**Comment by AxeOfMen** [comment]
Following the directions on your installation wiki [here](https://github.com/segmentio/chamber/wiki/Installation#debianubuntu-from-packagecloudio) leads to the error given by the OP.

**Comment by asaf-erlich** [comment]
Ok then I think the shortest answer to the question is the more stable place is going to be github release artifacts: https://github.com/segmentio/chamber/releases . And I'll create a backlog ticket for the team to double check why the package cloud instructions don't just work (I suspect they should but nothing is testing those unfortunately) and decide how we want to address that.

**Comment by asaf-erlich** [comment]
Jira backlog ticket created which links to this github issue. I'll try to get it discussed in one of our next backlog refinement meetings.
