### ISSUE TITLE
Chamber fails to save contents of a string if it starts with `--` because chamber thinks it's a switch

### ISSUE THREAD

**Issue by nitrocode** [segmentio/chamber#323]
Save this file to `newtext`

```
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
```

```
$ chamber write hello world "$(cat newtext)"
Error: bad flag syntax: -----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
```

And prefixing it with a space works

```
$ chamber write hello world " $(cat newtext)"
```

**Comment by estheruary** [comment]
You need to do something like

```
chamber write hello world -- "$(cat newtext)"
```

to tell chamber to stop processing flags.

If you run `chamber write --help` you will see the double dash in the usage string.

**Comment by nitrocode** [comment]
In the `chamber write --help` dialogue, I see the double dash but I was not aware of this usage.

It would be great to document this in the README.

Thanks @estheruary !
