### ISSUE TITLE
Cannot delete keys, which are uppercase

### ISSUE THREAD

**Issue by Rapiernik** [segmentio/chamber#324]
Hi there, 
I inherited legacy code, which is associated with Chamber. I see there different keys, where majority is in the form blabla_blabla. But there are some keys written in uppercase, e.g. BLABLA_BLABLA. I can't read them from console or delete them. I'm getting "Error: secret not found", even though I see them in a list. Is there anything I can do with it?

**Comment by yanigisawa** [comment]
FYI @Rapiernik - see this issue as well of others reporting the same issue. 

https://github.com/segmentio/chamber/issues/160

**Comment by AndresElizondo** [comment]
Have you read [this comment](https://github.com/segmentio/chamber/issues/160#issuecomment-550557063)?
> For anyone else hitting this, you can remove the uppercased keys with the awscli:
> `aws ssm delete-parameters --name "{service}/{KEY}"`

This unblocked my workflow. I agree a solution inside chamber is needed though.

**Comment by alecjacobs5401** [comment]
As of https://github.com/segmentio/chamber/releases/tag/v2.12.0, this can now be resolved with
```
chamber delete --exact-key
```

[Some more details in the README](https://github.com/segmentio/chamber#deleting)

This should provide the expected functionality in a non-breaking manner. In a future version, it is likely that this becomes the default behavior

**Comment by mckern** [comment]
Closing; we may reopen this in the future if we determine there is more work to do in this area.
