### ISSUE TITLE
Support Hierarchical Keys

### ISSUE THREAD

**Issue by RyanBowlby-Reflektion** [segmentio/chamber#33]
I'm still just exploring chamber but I'm confused on how to properly make use of hierarchical keys. Am I just to do underscores to mimic a hierarchy? Example:

`chamber write appname_env_region_mt keyfoo valuebar`

I believe parameter store has some ability to use `/` delimiter in keys? Is that not supported? I tried:

`→ chamber write /appname/env/region/mt keyfoo valuebar`

`Failed to validate service name '/appname/env/region/mt'.  Only alphanumeric, dashes, and underscores are allowed for service names`

We, rather unfortunately, do not have separate AWS accounts for each environment. Still, even if we did, we are multi-region and have both multi-tenant and customer specific clusters. Our need for key hierarchies would remain.

Perhaps I'm just doing it wrong?

**Comment by abraithwaite** [comment]
See https://github.com/segmentio/chamber/pull/23
