### ISSUE TITLE
doesn't seem to work with path based secret that starts with a '/'

### ISSUE THREAD

**Issue by robert-spring** [segmentio/chamber#333]
for some reason i need to remove the starting slash from my chamber calls:

``` 
chamber list-services /this/is/test 
```
returns nothing

```
chamber export /this/is/test  -f yaml
Error: Failed to validate service /this/is/test: Failed to validate service name '/this/is/test'.  Only alphanumeric, dashes, forwardslashes, fullstops and underscores are allowed for service names
```

it says it should be able to, but fails.
* if i remove the leading slash it works.

**Comment by alecjacobs5401** [comment]
Hi @robert-spring

This looks like an issue with the error message. Leading slashes in service names [aren't supported currently](https://github.com/segmentio/chamber/blob/79dd716042dbc826455bc9fe52290fe09a3d8c87/cmd/root.go#L20) so the error message is inaccurate in that reflection, which is a bug.

Thanks for reporting/asking the question!
