### ISSUE TITLE
chore: installation on darwin + Go 1.18

### ISSUE THREAD

**Issue by mrkagelui** [segmentio/chamber#349]
Hi, there seems to be two issues for this setup.

1. `go get` [is deprecated](https://go.dev/doc/go-get-install-deprecation) and yet in the readme and wiki, I think `go install github.com/segmentio/chamber/v2@latest` should be recommended
2. `go install` is also failing:

```command
➜  ~ go version
go version go1.18.2 darwin/amd64
➜  ~ go install github.com/segmentio/chamber/v2@latest
# golang.org/x/sys/unix
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.go:121:3: too many errors
```
it seems that https://stackoverflow.com/a/71508032 is related, and I think the solution would be to upgrade that dependency which is two years older.

**Comment by mrkagelui** [comment]
temporary workaround: install an old version by 

```command
go install github.com/segmentio/chamber@latest
```

**Comment by mrkagelui** [comment]
@asaf-erlich also https://github.com/segmentio/chamber/wiki/Installation#advanced-go-get needs to be updated with `go install` I think, unfortunately I don't think I can PR that one

**Comment by rikez** [comment]
@mrkagelui I'm trying to understand your request. Do you want to compile chamber in Go 1.18? Is this related to this [PR](https://github.com/segmentio/chamber/pull/350)?

**Comment by mrkagelui** [comment]
> @mrkagelui I'm trying to understand your request. Do you want to compile chamber in Go 1.18? Is this related to this [PR](https://github.com/segmentio/chamber/pull/350)?

yup, I think this can be closed once a new version is published

**Comment by sindhusegment** [comment]
@mrkagelui closing this issue as we have published a [new release](https://github.com/segmentio/chamber/tree/v2.10.11). Let us know if there are any issues!

**Comment by mrkagelui** [comment]
> @mrkagelui closing this issue as we have published a [new release](https://github.com/segmentio/chamber/tree/v2.10.11). Let us know if there are any issues!

Awesome, thanks! Let me try

**Comment by mrkagelui** [comment]
it's working for me! thanks

**Comment by asaf-erlich** [comment]
@mrkagelui I was out on vacation after your last comment. Thank you @sindhusegment and @rikez for taking care of the rest of this.

**Comment by mrkagelui** [comment]
> @mrkagelui I was out on vacation after your last comment. Thank you @sindhusegment and @rikez for taking care of the rest of this.

Welcome back!
