### ISSUE TITLE
Support camel-cased / snake-cased keys

### ISSUE THREAD

**Issue by nitrocode** [segmentio/chamber#357]
## problem

SSM supports case sensitive keys and passing in camel-cased / snake-cased keys

It's a surprise when I pass in the same cased keys to `chamber` and it then gets lowercased.

## possible solution

It would be nice if we the case you send is what you get or allow us to opt out of lowercasing the keys.

## references

- https://github.com/segmentio/chamber/issues/354

https://github.com/segmentio/chamber/blob/6bf478b26c3dd2e717a8558a44bdcec2624c19c1/cmd/write.go#L40

**Comment by mckern** [comment]
@nitrocode As of https://github.com/segmentio/chamber/releases/tag/v2.12.0, this can now be accomplished with the command `chamber import --normalize-keys`. @alecjacobs5401 has provided [some more details in the README](https://github.com/segmentio/chamber#importing). I believe that satisfies this bug report.
