### ISSUE TITLE
Security Scans flagging go-complier v1.13.15

### ISSUE THREAD

**Issue by dli-spoton** [segmentio/chamber#367]
Our security scanners are still finding `go-complier` version 1.13.15 on Chamber version 2.11.0.

I think it might be because the Dockerfile is building from `golang:1.13-alpine` [here](https://github.com/segmentio/chamber/blob/master/Dockerfile#L1).

Relates to: #363

**Comment by sindhusegment** [comment]
Hey @dli-spoton, we're working on this and should have a fix up soon: https://github.com/segmentio/chamber/pull/368. Thanks for letting us know.

**Comment by sindhusegment** [comment]
@dli-spoton This is mitigated in chamber [v2.11.1](https://github.com/segmentio/chamber/releases/tag/v2.11.1).

**Comment by sindhusegment** [comment]
completed in #368
