### ISSUE TITLE
consider adding semantic version info in "version" subcommand

### ISSUE THREAD

**Issue by mrkagelui** [segmentio/chamber#373]
currently, in order to find out the CLI version, the only way I can think of is to do `go version -m /path/to/cli`, `chamber version` does not seem to print anything beyond `chamber dev`. would you think it's more user friendly to add that info into `chamber version` subcommand?

**Comment by nitrocode** [comment]
I use `brew install chamber` and it contains the correct version

If you try go install or go get with the specific version, does it work? If not, it's probably because the version is passed in during the build process.

**Comment by mrkagelui** [comment]
> I use `brew install chamber` and it contains the correct version
> 
> 
> 
> If you try go install or go get with the specific version, does it work? If not, it's probably because the version is passed in during the build process.

Thanks for replying! However that's not the problem I'm trying to solve, unless I failed to understand you. I installed it via Go, and I can't determine the version of the CLI. Perhaps homebrew does keep track, but that's via brew CLI.

If it helps, one scenario where it'll be good for chamber CLI to print the version would be, I need to verify chamber version for some behavior, but I can't remember how I installed it

**Comment by nitrocode** [comment]
I'm not one of the maintainers here and I can only help dig into the code.

See the build process

https://github.com/segmentio/chamber/blob/85c59710834310ea817261b29c0a6351b9bb98bc/Makefile#L8
https://github.com/segmentio/chamber/blob/85c59710834310ea817261b29c0a6351b9bb98bc/Makefile#L20
https://github.com/segmentio/chamber/blob/85c59710834310ea817261b29c0a6351b9bb98bc/Makefile#L35-L36

The ldflags get the version from the tags and those flags are passed when building the app. If you run `go install`, it doesn't have the same ldflags so there is no knowledge of the version.

The same issue is seen in other golang apps that depend on goreleaser to inject the version.

You could clone the code and build the code yourself or you can run the install and manually add the ldflags.

**Comment by mckern** [comment]
To the best of my knowledge, short of hardcoding a version string that a person must remember to update on every release (ick), there's no deterministic way to make this available if you use `go install`. The information that the compiler embeds into the binary is accessible but seems to have no knowledge of SCM tags:

### Build with `make chamber`

```
chamber $ go version -m ./chamber
./chamber: go1.20.4
	path	github.com/segmentio/chamber/v2
	mod	github.com/segmentio/chamber/v2	(devel)
	dep	github.com/alessio/shellescape	v1.4.1	h1:V7yhSDDn8LP4lc4jS8pFkt0zCnzVJlG5JXy9BVKJUX0=
	dep	github.com/aws/aws-sdk-go	v1.44.257	h1:HwelXYZZ8c34uFFhgVw3ybu2gB5fkk8KLj2idTvzZb8=
	dep	github.com/google/uuid	v1.3.0	h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
	dep	github.com/jmespath/go-jmespath	v0.4.0	h1:BEgLn5cpjn8UN1mAw4NjwDrS35OdebyEtFe+9YPoQUg=
	dep	github.com/magiconair/properties	v1.8.7	h1:IeQXZAiQcpL9mgcAe1Nu6cX9LLw6ExEHKjN0VQdvPDY=
	dep	github.com/segmentio/analytics-go/v3	v3.2.1	h1:G+f90zxtc1p9G+WigVyTR0xNfOghOGs/PYAlljLOyeg=
	dep	github.com/segmentio/backo-go	v1.0.1	h1:68RQccglxZeyURy93ASB/2kc9QudzgIDexJ927N++y4=
	dep	github.com/spf13/cobra	v1.7.0	h1:hyqWnYt1ZQShIddO5kBpj3vu05/++x6tJ6dg8EC572I=
	dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
	dep	golang.org/x/sys	v0.8.0	h1:EBmGv8NaZBZTWvrbjNoL6HVt+IVy3QDQpJs7VRIw3tU=
	dep	gopkg.in/yaml.v3	v3.0.1	h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
	build	-buildmode=exe
	build	-compiler=gc
	build	-trimpath=true
	build	CGO_ENABLED=0
	build	GOARCH=amd64
	build	GOOS=darwin
	build	GOAMD64=v1
	build	vcs=git
	build	vcs.revision=7fab80106d3c0e67ec57957c99378afe1558cef8
	build	vcs.time=2023-05-11T02:13:37Z
	build	vcs.modified=true
```

### Build with `go build` (analogous to `go install`):

```
$ go version -m ./chamber
./chamber: go1.20.4
	path	github.com/segmentio/chamber/v2
	mod	github.com/segmentio/chamber/v2	(devel)
	dep	github.com/alessio/shellescape	v1.4.1	h1:V7yhSDDn8LP4lc4jS8pFkt0zCnzVJlG5JXy9BVKJUX0=
	dep	github.com/aws/aws-sdk-go	v1.44.257	h1:HwelXYZZ8c34uFFhgVw3ybu2gB5fkk8KLj2idTvzZb8=
	dep	github.com/google/uuid	v1.3.0	h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
	dep	github.com/jmespath/go-jmespath	v0.4.0	h1:BEgLn5cpjn8UN1mAw4NjwDrS35OdebyEtFe+9YPoQUg=
	dep	github.com/magiconair/properties	v1.8.7	h1:IeQXZAiQcpL9mgcAe1Nu6cX9LLw6ExEHKjN0VQdvPDY=
	dep	github.com/segmentio/analytics-go/v3	v3.2.1	h1:G+f90zxtc1p9G+WigVyTR0xNfOghOGs/PYAlljLOyeg=
	dep	github.com/segmentio/backo-go	v1.0.1	h1:68RQccglxZeyURy93ASB/2kc9QudzgIDexJ927N++y4=
	dep	github.com/spf13/cobra	v1.7.0	h1:hyqWnYt1ZQShIddO5kBpj3vu05/++x6tJ6dg8EC572I=
	dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
	dep	golang.org/x/sys	v0.8.0	h1:EBmGv8NaZBZTWvrbjNoL6HVt+IVy3QDQpJs7VRIw3tU=
	dep	gopkg.in/yaml.v3	v3.0.1	h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
	build	-buildmode=exe
	build	-compiler=gc
	build	-trimpath=true
	build	CGO_ENABLED=1
	build	GOARCH=amd64
	build	GOOS=darwin
	build	GOAMD64=v1
	build	vcs=git
	build	vcs.revision=7674fa9d2385f8a2f7f5cbcaf88ea8d3251565bd
	build	vcs.time=2023-05-11T23:17:50Z
	build	vcs.modified=true
```

If you need/want semantic versioning, then I suggest that you use one of our builds or download and build it using `make` yourself. If you know of a trick that we don't for retrieving tag information using `go install`, we're happy to investigate that path.
