### ISSUE TITLE
How do u install chamber?

### ISSUE THREAD

**Issue by hulkish** [segmentio/chamber#41]
This might be obvious to a go dev, so forgive me. But I see no mention of this throughout this repo, so I thought I'd ask.

**Comment by abraithwaite** [comment]
The easiest way is to install via download on the releases page:
https://github.com/segmentio/chamber/releases

Otherwise, if you want to install from tip and you have go installed: `go install github.com/segmentio/chamber`

**Comment by kylealwyn** [comment]
would be nice to install via homebrew
