### ISSUE TITLE
chamber crashes if description of the parameter is not defined

### ISSUE THREAD

**Issue by odzhu** [segmentio/chamber#43]
Hi Team,

Chamber fails when at least one parameter within service contains empty description.
Such limitation makes not possible to use terraform to provision parameters,
it doesn't have possibility to set description for ssm parameter.

I see you use "description" for versioning purposes, however, parameter store already enabled versioning out of the box.

Please have a look.

Problem:

**$chamber list testenv**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x809048]

goroutine 1 [running]:
github.com/segmentio/chamber/store.parameterMetaToSecretMeta(0xc4201c41c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/segmentio/chamber/store/ssmstore.go:310 +0x48
github.com/segmentio/chamber/store.(*SSMStore).List(0xc420013f40, 0x7fffd19327d3, 0x7, 0x0, 0x40ca5f, 0x8b0f00, 0xc420013afd, 0xc4200d5b87, 0xc420013afd)
	/go/src/github.com/segmentio/chamber/store/ssmstore.go:220 +0x80a
github.com/segmentio/chamber/cmd.list(0xc754a0, 0xc420013bd0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/segmentio/chamber/cmd/list.go:39 +0x105
github.com/segmentio/chamber/vendor/github.com/spf13/cobra.(*Command).execute(0xc754a0, 0xc420013b80, 0x1, 0x1, 0xc754a0, 0xc420013b80)
	/go/src/github.com/segmentio/chamber/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/segmentio/chamber/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc758e0, 0x4, 0xc75b00, 0xc75a20)
	/go/src/github.com/segmentio/chamber/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/segmentio/chamber/vendor/github.com/spf13/cobra.(*Command).Execute(0xc758e0, 0xc420056058, 0x0)
	/go/src/github.com/segmentio/chamber/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/segmentio/chamber/cmd.Execute()
	/go/src/github.com/segmentio/chamber/cmd/root.go:42 +0x31
main.main()
	/go/src/github.com/segmentio/chamber/main.go:6 +0x20

**Comment by dfuentes** [comment]
fixed by https://github.com/segmentio/chamber/pull/60
