### ISSUE TITLE
Allow using `CHAMBER_BACKEND` env variable to set the backend

### ISSUE THREAD

**Issue by nitrocode** [segmentio/chamber#436]
I'd prefer if I could use an env var `CHAMBER_BACKEND=secretsmanager` instead of setting the `--backend secretsmanager` every time.

Would maintainers be open to this?

**Comment by dfuentes** [comment]
You should be able to use the env var `CHAMBER_SECRET_BACKEND`

**Comment by nitrocode** [comment]
Oh you are completely right. Thank you. I'll close.

Is there a doc on all of these env vars?
