### ISSUE TITLE
Origin of the name chamber

### ISSUE THREAD

**Issue by nitrocode** [segmentio/chamber#440]
It's probably obvious. It didn't hit me until I was looking up movies and came across the 2nd movie, harry potter chamber of secrets.

Is this the origin? If so, it would be nice to add to the readme.

**Comment by bhavanki** [comment]
It is the origin. (I'm currently a Segment employee, and I dug around a bit in internal comms to confirm.)

**Comment by bhavanki** [comment]
Resolved via https://github.com/segmentio/chamber/pull/457 (a little indirectly)
