### ISSUE TITLE
"chamber write:" add option to read from os.Stdin

### ISSUE THREAD

**Issue by kevinburke** [segmentio/chamber#46]
If I run `chamber write service key`, I get an error about too few arguments.

Passing a secret value at the command line means it may leak into bash_history or e.g. audit tools that export all run commands to a third party server. This is one reason that Mysql's `-p` flag prompts you for the password by default when you enter it at the command line.

It would be nice if "chamber write" supported this same functionality.

**Comment by dfuentes** [comment]
Try `chamber write service key -`
