### ISSUE TITLE
Have a way to override KMS key alias with a file

### ISSUE THREAD

**Issue by robinjoseph08** [segmentio/chamber#47]
We plan on having a separate KMS key per service, so instead of having to pass in `CHAMBER_KMS_KEY_ALIAS` for every command, it would be nice if there was a `.chamber-kms-key-alias` (or something similar) file that chamber looks for in addition to the environment variable so that we can check that file into VCS and it's easier for developers to write secrets for different services.

Happy to put up a PR if this sounds good to you!

**Comment by ejcx** [comment]
@robinjoseph08 can you just set the environment variable in your profile? Seems like overkill to change the program when there is a simple fix available.

**Comment by robinjoseph08** [comment]
While that would work if we had one key with a different alias name, since we'll be having separate keys, it's a different alias for each service so we can't put it in our global profile.

**Comment by ejcx** [comment]
Oh my mistake I completely misread your comment. Separate KMS key per service is very aggressive.

Is this supposed to be an additional safety mechanism besides using SSM IAM policy? Is there a particular issue with using only one KMS key?

**Comment by robinjoseph08** [comment]
Right, it's more of an additional safety mechanism. We didn't see that there was any reason for a particular service to have the ability to decrypt the secrets of any other service (even though we're already limiting which ones it can get through SSM). It just seemed like an unnecessarily large scope for a service's permission.

**Comment by robinjoseph08** [comment]
Any additional thoughts on this? I'd love to submit a PR, but only if you guys think it makes sense?

Having separate KMS keys is a pretty hard requirement for us, and we really want to make it as easy as possible to write secrets (i.e. as few environment variables necessary as possible).

**Comment by FernandoMiguel** [comment]
this can be easily done via iam policies, and parameter prefix.
doing it at KMS level is overkill in my opinion
i posted an example in https://github.com/segmentio/chamber/issues/45#issuecomment-362606863

**Comment by eriksw** [comment]
On the flipside of this, I'd appreciate a way to *not* use a customer-managed key _at all_, and instead just use the default AWS-managed key. There's relatively few reasons to use customer-managed keys *if* you grant `kms:Decrypt` permissions sparingly: i.e. with a condition on the `PARAMETER_ARN` [encryption context key](https://docs.aws.amazon.com/kms/latest/developerguide/encryption-context.html).

**Comment by jdub** [comment]
@eriksw You can use `CHAMBER_KMS_KEY_ALIAS=aws/ssm chamber …`. I'd even suggest that would be the better default.

**Comment by nickatsegment** [comment]
Out of scope I'd say.
