### ISSUE TITLE
Incorrect escape of exclamation mark in export

### ISSUE THREAD

**Issue by mwisnicki** [segmentio/chamber#485]
I have an exclamation mark in the middle of value: `"a!b"`

Export with `chamber env foo` works fine but `chamber export --format dotenv foo` incorrectly escapes the excalamation to `"a\!b"`. The same thing happens with tfvars format.

**Comment by bhavanki** [comment]
For the dotenv format: The escaping of the exclamation point derives from https://github.com/joho/godotenv, which explicitly includes it among characters needing escaping. There is a godotenv [issue](https://github.com/joho/godotenv/issues/172) about this, but the (former) repo maintainer claims that the escaping is correct to maintain compatibility with the [Ruby](https://github.com/bkeepers/dotenv) and [node](https://github.com/motdotla/dotenv) dotenv libraries. So, escaping is probably the right thing to do.

We could add an option to avoid escaping exclamation points, but then the resulting file wouldn't be in correct dotenv format. (It _would_ make it directly consumable by the shell, though ... probably.) Another choice is to make a new output format like `shell` which doesn't do the escaping.

**Comment by mwisnicki** [comment]
It seems like that maintainer is asking rather than claiming that is the behavior ruby/node. Someone will need to check it.

**Comment by mwisnicki** [comment]
Tested with ruby and it works as expected:
```
echo 'FOO="1!2"' > .env 
gem install dotenv
ruby -r 'dotenv/load' -e 'puts ENV["FOO"]'
```
Returns `1!2`

**Comment by mwisnicki** [comment]
Same thing with node:

```
npm install dotenv
node -e 'require("dotenv").config(); console.log(process.env.FOO)'
```

Outputs: `1!2`

No need for incorrect escape of `!`.

**Comment by mwisnicki** [comment]
And it is generally assumed `.env` files have format that can be sourced from shell:

https://github.com/search?q=%22source+.env%22+language%3AShell&type=code&l=Shell

**Comment by bhavanki** [comment]
Thank you for all that legwork! 🙏 I'm convinced.

If you'd like to submit a PR yourself to fix chamber, please do. I recently made sure that our [contributing guidelines](https://github.com/segmentio/chamber/blob/master/CONTRIBUTING.md) were still valid.
