### ISSUE TITLE
Feature Request: Don't update value if there is no change

### ISSUE THREAD

**Issue by jro** [segmentio/chamber#50]
It would be great if chamber doesn't update the value on a key-value pair when the "new" value is the same as the existing. This prevents superfluous items being added to the history either by mistake or automation.

**Comment by bhound** [comment]
jro, sorry for bugging you on multiple platforms but I would like to discuss something if possible.

**Comment by ejcx** [comment]
I actually implemented this feature but do not really like the idea.

Making chamber do a read before it does a write changes the IAM requirements for the user doing the write, and means nobody using chamber can write if they don't have read capabilities.

We _do_ have the use case for having one service writing secrets for all services (like auth credentials), but this service shouldn't be able to read all services other secrets.
