### ISSUE TITLE
Feature request: export -f dotenv 

### ISSUE THREAD

**Issue by jeffnappi** [segmentio/chamber#74]
Hi guys, thanks for your work on chamber and all the open communication you've been publishing with regards to Terraform, AWS, aws-vault, etc. It's very helpful to a lot of people.

Here's a simple feature that I'd like to see: Instead of using environment variables, I would prefer to store the secrets in a `.env` file. And I'd like to populate that `.env` file via chamber.

I propose adding a format option to `export` of `dotenv`. I envision it working like so:
```
chamber export service_name -f dotenv
```
The output would simply be VARIABLE=value rows:

```
SECRET_KEY=abc
FREE_TACOS=true
```
etc.

In production, we'd simply run something along the lines of `chamber export service_name -f dotenv > config/.env`.

This way, we make it a little tougher to accidentally leak secrets through environment debug logs, etc that may crop up from 3rd party executables.

If there's interest in this, I may be able to find the time to implement it myself and send over a PR.

**Comment by ejcx** [comment]
I personally feel pretty strongly that ENV VARs are the right way to inject secrets, but I think it's kind of a religious battle so I think chamber should probably support it.

We would be happy for you to send a PR.

**Comment by dfuentes** [comment]
This was easy enough to add quickly, https://github.com/segmentio/chamber/pull/75

**Comment by jeffnappi** [comment]
Hey @dfuentes that was lightning fast :) 

@ejcx I appreciate that sentiment - at the moment I am using environment variables. So I'd like to hear your thoughts in more detail (I'll DM you).
