### ISSUE TITLE
Workarounds for DescribeParameters Rate-Limits

### ISSUE THREAD

**Issue by djrodgerspryor** [segmentio/chamber#76]
## Summary
I've been experimenting with using chamber to load and manage secrets for our micro-service app and been running head-first into AWS throttling for calls to the DescribeParameters API. I'd like to explore ways of mitigating these limits in chamber.

## Prior Work
Other people seem to have hit similar problems in the past:
 - https://github.com/segmentio/chamber/issues/34
 - https://github.com/segmentio/chamber/pull/36
 - https://github.com/segmentio/chamber/pull/54

## Problem Statement
When we bring up a bunch of new services (eg. when scaling-up or creating a new stack for blue-green deployment), we run `chamber exec` or `chamber export` in each of our docker containers to load the secrets for that process. Chamber then calls DescribeParameters to list the available parameter names for the service, which then hangs during exponential backoff in the AWS SDK until it succeeds (for the first few containers) then runs-out of retries and fails for the rest.

We've tried increasing the number of retries, but it just takes too long (which is a big problem if we're bringing-up new containers to scale out-of an increase in load). The AWS rate-limit appears to be very low (less than one per second).

## Solutions
Obviously the best solution would be to increase the AWS rate-limits, but they seem very unwilling to do that for DescribeParameters (they insist that it should only be used for manual querying on a CLI). I've created this issue to gauge interest and survey ideas for building some sort of workaround into chamber.

Whatever we build will need to find some alternate way of listing the relevant parameters, then just query for their latest values using GetParameters (which has much higher limits). Here are some ideas I've been thinking about:

* Option 1: **Cache parameter names in a file.** Dump the parameter names to a file (eg `.chamber-<service-name>-cache.json`) after successfully running DescribeParameters, then read them from the file next-time (if the caller provides the `--use-cache` option), with some freshness limit on the modification time of the file (eg. 1 hour). This would work transparently most of the time, but also let users pre-generate and ship-around the cache files as build artefacts if they wanted.
* Option 2: **Pass in the parameter names as arguments.** This is simple, but ugly. It forces everyone with this problem to come-up with their own scheme for caching and/or shipping-around parameter names, but it also gives maximum flexibility about how to do that.
* Option 3: **Cache the full list of names as a parameter-store parameter.** When the chamber CLI writes/deletes a parameter, it could fetch the full (updated) list of parameter names and store it in an (unencrypted?) parameter (eg. `<service-name>.chamber-internal-parameter-name-cache`). Then it could optionally use the value of that parameter as a cache when reading. This is the most magic and transparent solution, but it will be confusing when it breaks and it has some awkward edge-cases (eg. hitting the max parameter value size, race-conditions between chamber instances to update the list, restrictive permissions on IAM roles for reading/writing to the internal parameter).

Maybe there's a better solution I haven't thought-of; I'd love input from anyone else who's had this problem and found a work-around.

**Comment by djrodgerspryor** [comment]
Hmm, actually, on second glance, the AWS API appears to support a GetParametersByPath method (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html). If we use path-formatted keys, then we might be able to just use that instead of DescribeParameters.

I'll have a crack at implementing that.

If it works, we should probably consider making path-based keys the default in a major version change at some point soon, since it would save users from this problem down the road.

**Comment by dfuentes** [comment]
Thanks for the investigation.  I like option 3, as its something we could implement transparently and in a backwards compatible manner.

I'm pretty hesitant to change the default behavior in such a breaking way as to make paths default, but it's something to consider.

**Comment by djrodgerspryor** [comment]
After some experimentation, it seems like the GetParametersByPath is a really easy win without any of the trade-offs of the other options.

I've submitted a PR here: https://github.com/segmentio/chamber/pull/79

**Comment by dfuentes** [comment]
Quick update.  First, thanks for the PR!  Second, I've just released chamber 2.0 which makes the paths use case the default.

**Comment by djrodgerspryor** [comment]
Great! Thanks for the quick responses.
