### ISSUE TITLE
Using different environments in ENTRYPOINT

### ISSUE THREAD

**Issue by gconaty** [segmentio/chamber#77]
First of all, thank you for creating this solution.  What solution do you use for letting the parameter vary in the entrypoint?  e.g. `ENTRYPOINT ["chamber", "exec" "someenv", "--"]`?  This changes for us in each cluster we setup.  It's simple to have in an entrypoint but Docker doesn't support passing variables there.  The only other solution I can think of is to not have chamber be the entrypoint but have a different init process.  thanks.

**Comment by ejcx** [comment]
One pattern we have used is we've made the entrypoint a small shell-script, which handles the invocation of the program and chamber. Would that help you? 

```
ENTRYPOINT ["./run.sh"]
```

Inside run.sh:
```
#!/bin/bash
exec chamber exec $SOMEENV -- ...
```

**Comment by gconaty** [comment]
Thanks Evan. Turns out I ended up using `tini` as the entrypoint with `CMD ["chamber","exec","staging","--","node","server/server.js"] and it's working fun.  For some reason I was hoping that AWS service definitions would allow for container overrides like you can when running tasks but no such luck.  So I'm still stuck with multiple task definitions that only differ by their `CHAMBER_ENV` :)
