### ISSUE TITLE
Developing & Prod with Chamber

### ISSUE THREAD

**Issue by drjaydenm** [segmentio/chamber#78]
Hello there, I have a question about using chamber, not sure if this is the best place to ask it, please feel free to redirect me somewhere else :)

I have read your article [The right way to manage secrets](https://segment.com/blog/the-right-way-to-manage-secrets/) and was just wondering how your developers are using chamber locally with Docker to develop offline. My understanding is that chamber connects to the AWS Parameter Store to fetch credentials (which wouldn't work offline). I see that aws-vault has a local server mode - does this fulfill that purpose somewhat?

My question is twofold:

1. How do you keep the code calling chamber in Dockerfiles (the entrypoint) the same for prod and development? As I understand aws-vault is required to be used locally, while not required in prod due to EC2/ECS IAM roles.

2. Can you use chamber offline whilst starting Docker containers with some sort of dummy Parameter Store? How do your developers accomplish this?

Thanks in advance :)

**Comment by abraithwaite** [comment]
Most of us don't use chamber to develop locally.  Most of our projects have an associated docker-compose file with appropriate scaffolding to start developing with empty databases.  In the projects I work on, I leave the entrypoint empty and specify the whole command to docker run or ECS (or insert your container runtime / orchestration of choice here).

There are some workarounds you can do with scripts, but I prefer my way (of course).

We do not use chamber offline and do not have a magical mock parameter store to my knowledge.

**Comment by drjaydenm** [comment]
Thanks for that. Could I just clarify how you are doing/would do it for scenarios with multiple containers that need to share keys to communicate?

- Local development: You pass in the secrets to use for these containers as part of the `docker run` command?
- Prod: In the ECS task definition, you use chamber to grab the secrets from parameter store and then pass these on to whatever service is going to be running in that container?

**Comment by abraithwaite** [comment]
> You pass in the secrets to use for these containers as part of the docker run command?

In an isolated environment, yes.  We typically configure our services through the environment (just like chamber) so it's easy to source a file with our local secrets, or just pass them through the CLI.

In prod, we execute chamber inside the docker which is running the service we want to configure.  Chamber then exec's the subsequent command with it's environment populated with the secrets.

**Comment by drjaydenm** [comment]
Thanks for your help, that clears it up for me
