### ISSUE TITLE
Command line version flag (and possible update check)

### ISSUE THREAD

**Issue by jeffnappi** [segmentio/chamber#81]
It would be nice to have a `--version` flag to double check which version of chamber you have installed.

A small upgrade to that would be checking the latest release and linking to the download à la Terraform:
```
$ terraform --version
Terraform v0.11.2

Your version of Terraform is out of date! The latest version
is 0.11.5. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by dfuentes** [comment]
I have added a `version` subcommand along with the 2.0 release

**Comment by jeffnappi** [comment]
@dfuentes Thank you! I really appreciate that. And also, thank you for getting 2.0 out - I am just about to roll out chamber for the first time and now I'll be able to go straight to `paths` in a clean manner.

:beers:
