### ISSUE TITLE
Does chamber support multiple environments in the same region?

### ISSUE THREAD

**Issue by vood** [segmentio/chamber#82]
Great tool. I discovered chamber via an article on AWS blog.

My question is the following: does chamber support multiple environments in one region?

For historical reasons, we run two different environments in the same region but in different VPC. I'd love to use chamber to manage our secrets but seems like there is no easy way to do so. To support such functionality chamber needs to support some sort of namespaces/prefixes in the parameter store's key name. 

Right now the key name format is the following:
```service_name/key_name```

Does chamber something like:
```namespace/service_name/key_name```

Thanks in advance!

**Comment by vood** [comment]
After more digging, I realized that https://github.com/segmentio/chamber/pull/70 potentially solves this

**Comment by nickatsegment** [comment]
Probably fixed.
