### ISSUE TITLE
Chamber clear env except chamber vars before exec

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/chamber#83]
I believe this would be a nice feature to have particularly for debugging.

Seeing the environment passed through from a command line, it can sometimes be hard to see which environment variables are being set by chamber.

**Comment by osterman** [comment]
Consider using `env` together with `chamber`.

e.g.

```
env -i chamber exec ....
```

Per the man page: 
>  -i      Execute the utility with only those environment variables specified by name=value options.  The environment inherited by env is ignored completely.

**Comment by abraithwaite** [comment]
Nice!  Clever and simple.

Expanding on this a bit, I believe we still need a subset of environment variables pertaining to the secret managers (AWS vars, others if the backends come to fruition).

```
10:54:01 $ env -i A=B /usr/local/bin/chamber exec app -- env
Error: Failed to list store contents: MissingRegion: could not find region configuration
```

Playing around with it a bit, it seems like stacking it with other commands might be a bit error prone:

```
11:00:46 $ aws-okta exec production -- env -i AWS_REGION=$AWS_REGION /usr/local/bin/chamber exec app -- env
Error: Failed to list store contents: MissingRegion: could not find region configuration
```

I'll see what I can do.
