### ISSUE TITLE
Alpine package?

### ISSUE THREAD

**Issue by bee-keeper** [segmentio/chamber#90]
Hi,

Thanks for this tool - is there any interest in creating an Alpine package for it?

**Comment by osterman** [comment]
Fwiw, we distributed chamber as an alpine package. 

https://github.com/cloudposse/packages

**Comment by nickatsegment** [comment]
I personally would love and use an alpine package. Building the package itself probably wouldn't be that much work to figure out. But hosting it in a repo might be. We're currently using packagecloud.io for official packages, and they don't support Alpine repos :( Figuring out hosting an Alpine repo seems like a fair amount of work and maintenance that I don't see Segment taking on in the near future.

I haven't tried cloudposse and can't really vouch for them, but it seems worth a shot (thanks @osterman). I added it as an unofficial repo at https://github.com/segmentio/chamber/wiki/Installation

**Comment by osterman** [comment]
Thanks @nickatsegment ! Fwiw, self-hosting an Alpine repository is very easy (CloudFormation+Lambda+S3 bucket). 

Here's a turn key solution that we use:
https://github.com/cloudposse/alpinist, which is a fork of https://github.com/forward3d/alpinist

**Comment by nickatsegment** [comment]
While I'd like to support an official Alpine package, it's slightly too much maintenance burden for us considering we don't have an Alpine repo for anything else. Plus, I think [copying the binary in using the Docker image](https://github.com/segmentio/chamber/pull/186) is easier. If Packagecloud gets Alpine support or Segment finds a broader need for Alpine packages, I'd revisit then.
