### ISSUE TITLE
Feature Request: Output shell script to set environment variables

### ISSUE THREAD

**Issue by omerxx** [segmentio/chamber#94]
Like using `exec` for a specific process, something like `chamber populate` will grab secrets and then evaluate them or `export` into the current environment.

**Comment by otterley** [comment]
Hi!  Can you tell us about your use case?

It's not possible for a child process to manipulate the environment of its caller, so what you're asking for isn't technically possible.  Specifically, `chamber` is a child process of the shell from which you're invoking it -- once `chamber` exits, any environment variables it sets disappear along with it.

There are a few workarounds possible.

One is to make `chamber` have a mode that emits a shell script that can then be evaluated by the invoking shell.  You'd then capture the environment variables by invoking it like `eval "$(chamber export)"`.

The other option, which you can use without any modifications to Chamber, is to run something like `exec chamber exec ... /bin/bash`.  This substitutes the current shell process with one that has been populated with the environment variables from Parameter Store.

**Comment by omerxx** [comment]
@otterley Hi, my use case is populating secrets to an environment that runs locally.
I thought about something like your second option with `eval "$(chamber export)"`
If you think that this is not a good use then you can drop it...

Anyway, chamber is truly awesome. our production is using it completely now and I've written a blog post about it - https://medium.com/prodopsio/managing-application-secrets-on-aws-with-ssm-and-chamber-3615d08cc599

Kudos!

**Comment by otterley** [comment]
I've updated the title to better describe your request.  Specifically, something like a `chamber env` that prints a shell script that can be `eval`'ed by the caller.

**Comment by jradtilbrook** [comment]
This sounds like quite a useful addition. I'd be willing to give it a go if no one else has elected to do it and/or you need some help. Let me know

**Comment by nickatsegment** [comment]
@jradtilbrook 	Go for it! 

One thing you'd have to watch out for is safe shell quoting. That's non-trivial code; maybe there's a library out there to do it for us

**Comment by jradtilbrook** [comment]
Sounds good. I've found this pretty simple library, https://github.com/alessio/shellescape. Are you happy for me to use that?

**Comment by alessio** [comment]
@nickatsegment proposal accepted - I'll rename the tool shortly :)
