### ISSUE TITLE
Document IAM JSON necessary to read KMS keys

### ISSUE THREAD

**Issue by kevinburkeomg** [segmentio/chamber#98]
I'm currently in the process of reverse engineering this, and it would be nice to know exactly what you need to put in the IAM permission JSON to be able to access your KMS keys.

**Comment by phantomwhale** [comment]
We've ended up with just:

```
    - kms:Decrypt
    - kms:DescribeKey
```

But that was through trial and error; might not be the best answer

**Comment by nickatsegment** [comment]
Duplicate: https://github.com/segmentio/chamber/issues/45
