### ISSUE TITLE
Can I use chamber as a package in my own Go tool instead of installation?

### ISSUE THREAD

**Issue by omerxx** [segmentio/chamber#99]
Hi, Chamber is awesome and I use it for our deployments.
I'm building a tool that deploys one of our components and I'd like to read a parameter using chamber. I don't want the executor to be forced to install Chamber.
I thought about importing the chamber package and use the code.
All I need is the `read` ability to fetch one value.

Any hints/ideas on how to do that and whether that's even possible?

**Comment by otterley** [comment]
It's not currently possible at the moment.  Chamber's largely a convenience wrapper over the Parameter Store AWS API, so it might be easiest for the moment to use the API.  See, e.g., https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.GetParameters
